<a href="https://colab.research.google.com/github/Ilya-2/R-practic/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практическая работа 1

## Задача 1

Вычислите в R:

* $67 ^ 3 - 112 ^ 2$;
* $\log(125)$;
* $\log_3(81)$.

In [ ]:
one <- 67 ** 3 - 112 ^ 2
print(one)
two <- log(125)
print(two)
three <- log(81,3)
print(three)

[1] 288219
[1] 4.828314
[1] 4

## Задача 2

В векторе `flights_d` сохранено число вылетов из аэропорта А, а в векторе `flights_a` — число прилётов в этот аэропорт за неделю.

In [ ]:
flights_d <- c(140, 150, 100, 90, 230, 240, 165)
flights_a <- c(65, 145, 80, 87, 220, 268, 216)

Используя R, ответьте на вопросы. Приведите код R, используемый для ответа на вопросы.

**2.1.** Сколько вылетов из аэропорта А было зафиксировано в среду?

In [ ]:
sr <- flights_d[3]
cat("Вылеты в среду:", sr)

Вылеты в среду: 100

**2.2.** На сколько число вылетов во вторник больше числа прилётов во вторник?

In [ ]:
razn <- flights_d[2] - flights_a[2]
cat("Разница вылетов и прилетов во вторник:", razn)

Разница вылетов и прилетов во вторник: 5

**2.3.** Во сколько раз число вылетов в воскресенье больше числа прилётов в воскресенье?

In [ ]:
vsk_razn <- flights_d[7] / flights_a[7]
cat("Во сколько раз вылеты в воскресенье больше прилетов:", vsk_razn)

Во сколько раз вылеты в воскресенье больше прилетов: 0.7638889

**2.4.** Сколько всего вылетов из аэропорта А было зафиксировано за неделю?

In [ ]:
sumd <- sum(flights_d)
cat("Всего вылетов за неделю:", sumd)

Всего вылетов за неделю: 1115

**2.5.** В какие дни недели число прилётов не превышает 220? Ответ подразумевает номера дней недели от 1 до 7.

In [ ]:
res_day <- which(flights_a <= 220)
cat("Дни недели, когда число прилетов не превышает 220:", res_day)

Дни недели, когда число прилетов не превышает 220: 1 2 3 4 5 7

## Задача 3

В векторе `cats` сохранены значения весов кошек в килограммах:

In [ ]:
cats <- c(4.765, 3.230, 1.256, 1.780, 2.583, 2.781, 3.945, 2.345)

**3.1.** Используя R, выведите ответы на вопросы.
* Сколько всего кошек было взвешено?

In [ ]:
res_sumk <- length(cats)
cat("Всего кошек:", res_sumk)

Всего кошек: 8

* Какой вес был у самой тяжёлой кошки? А у лёгкой?

In [ ]:
res_max_kg <- sort(cats)[length(cats)]
res_min_kg <- sort(cats)[1]
cat("Вес самой тяжелой кошки:",res_max_kg, "\n")
cat("Вес самой легкой кошки:", res_min_kg)

Вес самой тяжелой кошки: 4.765
Вес самой легкой кошки: 1.256

**3.2.** Создайте вектор `cats.round` со значениями весов кошек в килограммах, округлённых в меньшую сторону.

In [ ]:
cats.round <- floor(cats)
cat("Округление в меньшую сторону:", cats.round)

Округление в меньшую сторону: 4 3 1 1 2 2 3 2

**3.3.** Создайте вектор `cats_g` со значением весов кошек в граммах.

In [ ]:
cats_g <- cats * 1000
cat("Значение в граммах:", cats_g)

Значение в граммах: 4765 3230 1256 1780 2583 2781 3945 2345

## Задача 4

Согласно данным сайта <https://milknews.ru/> на сентябрь 2019 года, средние цены за килограмм сырого молока в Ненецком автономном округе, Камчатском крае, Москве, Республике Бурятия, Ивановской и Ленинградской областях были следующими:

In [ ]:
milk <- c(89.5, 50.5, 31.5, 21.0, 22.1, 27.4)

**4.1.** Не используя готовых функций для вычисления среднего значения, посчитайте среднее арифметическое по вектору `milk` и сохраните его в переменную (назовите её по своему усмотрению).

In [ ]:
avg_milk <- sum(milk) / length(milk)
cat('Среднее арифметическое:', avg_milk)

Среднее арифметическое: 40.33333

**4.2.** Одним из показателей разброса значений относительно среднего является выборочная дисперсия, которая вычисляется следующим образом:

$$
s^2 = \frac{\sum\limits_{i=1}^{n}(x_i-\bar{x})^2}{n-1},
$$

где $i$ — номер элемента в векторе, $\bar{x}$ — среднее арифметическое, $n$ — число элементов в векторе. Другими словами, для вычисления дисперсии необходимо из каждого элемента вычесть среднее, возвести полученные разности в квадрат, все просуммировать и поделить на число элементов, уменьшенное на 1.

Используя результат пункта 4.1, вычислите выборочную дисперсию для вектора `milk`. Сохраните результат в переменную (назовите её по своему усмотрению) и выведите на экран сообщение в одну строку вида «выборочная дисперсия равна: значение», где вместо слова «значение» подставлен полученный результат.

In [ ]:
n <- length(milk)
squared_diffs <- (milk - avg_milk)^2
variance <- sum(squared_diffs) / (n - 1)
cat('Выборочная дисперсия равна:', variance)

Выборочная дисперсия равна: 694.4507

## Задача 5

Встроенный в R вектор `euro` содержит стоимость 1 евро в национальных европейских валютах на 1998 год:

In [ ]:
euro

        ATS         BEF         DEM         ESP         FIM         FRF
  13.760300   40.339900    1.955830  166.386000    5.945730    6.559570
        IEP         ITL         LUF         NLG         PTE
   0.787564 1936.270000   40.339900    2.203710  200.482000

**5.1.** Запросите помощь по вектору `euro` и прочитайте информацию про него.

In [ ]:
help(euro)

**5.2.** Используя элементы вектора `euro`, определите, какой сумме в евро соответствует

* 100 финских марок;
* 50 бельгийских франков.

In [ ]:
convert_fim_euro <- 100 / euro['FIM']
cat('100 финских марок =', convert_fim_euro, 'евро', '\n')
convert_bef_euro <- 50 / euro['BEF']
cat('50 бельгийских франков =', convert_bef_euro, 'евро')

100 финских марок = 16.81879 евро
50 бельгийских франков = 1.239468 евро

**5.3.** Используя элементы вектора `euro`, определите, в какой европейской валюте 1 евро «весит» больше всего. Ответ необходимо дать в виде индекса этой валюты в векторе `euro`. Решение может занимать более одной строки. Использовать функции, не обсуждаемые в рамках модуля, например готовую функцию `max()`, нельзя.

In [ ]:
res <- which(euro == sort(euro, decreasing = TRUE)[1])
cat('Индекс валюты с максимальным значением:', res)

Индекс валюты с максимальным значением: 8

## Задача 6

Известно, что в таблице хранятся показатели по трём странам за пять лет. Фрагмент таблицы выглядит так:

| **country** | **year** |
|---------|------|
| France  | 2000 |
| France  | 2001 |
| France  | 2002 |
| France  | 2003 |
| France  | 2004 |
| Italy   | 2000 |
| Italy   | 2001 |
| Italy   | 2002 |
| Italy   | 2003 |
| Italy   | 2004 |
| Spain   | 2000 |
| Spain   | 2001 |
| Spain   | 2002 |
| Spain   | 2003 |
| Spain   | 2004 |

**6.1.** Создайте вектор `country` с названиями стран, то есть вектор, который послужил бы первым столбцом таблицы выше.

In [ ]:
country <- rep(c('France', 'Italy', 'Spain'), each = 5)
cat(country)

France France France France France Italy Italy Italy Italy Italy Spain Spain Spain Spain Spain

**6.2.** Создайте вектор `year` с годами, который мог бы послужить вторым столбцом таблицы выше.

In [ ]:
year <- rep(c(2000, 2001, 2002, 2003, 2004), 3)
cat(year)

2000 2001 2002 2003 2004 2000 2001 2002 2003 2004 2000 2001 2002 2003 2004

#Практическая работа 2

## Задача 1

Ниже приведено описание показателей, взятых из документации к результатам опроса:

* `ID`: id респондента, целочисленный тип;
* `GENDER`: пол, факторный тип (значения: 1 — женский, 2 — мужской);
* `YEAR`: год рождения, целочисленный тип.

Даны векторы, в которых сохранены несколько случайно выбранных значений из показателей, описанных выше:

In [ ]:
ID <- 100:108
GENDER <- c(1, 2, 2, 1, 2, 1, 1, 1)
YEAR <- c("1983", " 1988", "1975 ", "1980", "1977  ", "1992", "1994", "1983 ")

**1.1.** Проверьте, к какому типу относятся векторы (числовой, целочисленный, логический, строковый, факторный).

In [ ]:
str(ID)
str(GENDER)
str(YEAR)

 int [1:9] 100 101 102 103 104 105 106 107 108
 num [1:8] 1 2 2 1 2 1 1 1
 chr [1:8] "1983" " 1988" "1975 " "1980" "1977  " "1992" "1994" "1983 "

**1.2.** Если тип какого-то вектора не соответствует заявленному в описании выше, исправьте это, сохранив изменения в самом векторе. Среди приведённых выше векторов «неправильных» может быть несколько.

In [ ]:
GENDER <- as.factor(GENDER)
YEAR <- as.integer(YEAR)

str(GENDER)
str(YEAR)

 Factor w/ 2 levels "1","2": 1 2 2 1 2 1 1 1
 int [1:8] 1983 1988 1975 1980 1977 1992 1994 1983

## Задача 2

В таблицах ниже приведены данные по объёму экспорта и импорта товаров в долларах США за 2019 год для трёх стран (данные проекта [COMTRADE](https://comtrade.un.org/)).

**2.1.** Создайте датафреймы `goods_export` и `goods_import`, которые выглядят так, как таблицы с данными выше.

In [ ]:
goods_export <- cbind.data.frame('Партнёр 1' = rep(c('Канада', 'Нидерланды', 'США'), each=2), 'Партнёр 2' = c('Нидерланды', 'США', 'Канада', 'США', 'Канада', 'Нидерланды'),
'Экспорт (доллары США)' = c(3905228446, 336531873909, 4862948109, 29807484356, 292338433401,
51225636600))

goods_export

goods_import <- cbind.data.frame('Партнёр 1' = rep(c('Канада', 'Нидерланды', 'США'), each=2), 'Партнёр 2' = c('Нидерланды', 'США', 'Канада', 'США', 'Канада', 'Нидерланды'),
'Импорт (доллары США)' = c(3515239399, 229687088046, 2249551077, 42262861193, 326628559104, 30883263358))

goods_import

  Партнёр 1  Партнёр 2  Экспорт (доллары США)
1 Канада     Нидерланды   3905228446
2 Канада     США        336531873909
3 Нидерланды Канада       4862948109
4 Нидерланды США         29807484356
5 США        Канада     292338433401
6 США        Нидерланды  51225636600

  Партнёр 1  Партнёр 2  Импорт (доллары США)
1 Канада     Нидерланды   3515239399
2 Канада     США        229687088046
3 Нидерланды Канада       2249551077
4 Нидерланды США         42262861193
5 США        Канада     326628559104
6 США        Нидерланды  30883263358

**2.2.** На основе данных из таблиц 1 и 2 создайте матрицы `export_mat` и `import_mat`, которые будут в более компактном виде хранить информацию об экспорте и импорте. Это должны быть квадратные матрицы (число строк равно числу столбцов), по строкам и столбцам должны идти названия стран: Канада, Нидерланды, США.

In [ ]:
name <- c("Канада", "Нидерланды", "США")
export_mat <- matrix(0, nrow = 3, ncol = 3, dimnames = list(c(name),c(name)))

export_mat["Канада", "Нидерланды"] <- 3905228446
export_mat["Канада", "США"] <- 336531873909
export_mat["Нидерланды", "Канада"] <- 4862948109
export_mat["Нидерланды", "США"] <- 29807484356
export_mat["США", "Канада"] <- 292338433401
export_mat["США", "Нидерланды"] <- 51225636600

cat(export_mat)

import_mat <- matrix(0, nrow = 3, ncol = 3, dimnames = list(c(name), c(name)))

import_mat["Канада", "Нидерланды"] <- 3515239399
import_mat["Канада", "США"] <- 229687088046
import_mat["Нидерланды", "Канада"] <- 2249551077
import_mat["Нидерланды", "США"] <- 42262861193
import_mat["США", "Канада"] <- 326628559104
import_mat["США", "Нидерланды"] <- 30883263358

cat(import_mat)

0 4862948109 292338433401 3905228446 0 51225636600 336531873909 29807484356 00 2249551077 326628559104 3515239399 0 30883263358 229687088046 42262861193 0

**2.3.** Используя матрицы из пункта 2.2, создайте матрицу `diff_mat`, которая содержит разницу между экспортом и импортом стран.

In [ ]:
diff_mat <- export_mat - import_mat
print(diff_mat)

                 Канада  Нидерланды          США
Канада                0   389989047 106844785863
Нидерланды   2613397032           0 -12455376837
США        -34290125703 20342373242            0

**2.4.** Используя матрицы из пункта 2.2, создайте матрицы с логарифмированными (десятичный логарифм) значениями экспорта и импорта. Назовите матрицы по своему усмотрению.

In [ ]:
log_mat_export <- log10(export_mat)
log_mat_import <- log10(import_mat)

print(log_mat_export)

print(log_mat_import)

             Канада Нидерланды      США
Канада         -Inf   9.591646 11.52703
Нидерланды  9.68690       -Inf 10.47433
США        11.46589  10.709487     -Inf
              Канада Нидерланды      США
Канада          -Inf   9.545955 11.36114
Нидерланды  9.352096       -Inf 10.62596
США        11.514054  10.489723     -Inf

**2.5.** Создайте список `L_data`, который содержит следующие элементы:

* элемент `source` со значением "COMTRADE, https://comtrade.un.org/";
* элемент `year` со значением "2019";
* элемент `countries` — вектор с названиями стран (как в матрицах);
* элемент `export` — датафрейм `goods_export`;
* элемент `import` — датафрейм `goods_import`;
* элемент `export_mat` — матрица `export_mat`;
* элемент `import_mat` — матрица `export_mat`.

In [ ]:
country <- c("Канада", "Нидерланды", "США")
L_data <- list(source = 'COMTRADE, https://comtrade.un.org/', year = "2019",
countries = c(country), export = goods_export, import = goods_import, 'export_mat' = export_mat, 'import_mat' = import_mat)

print(L_data)

$source
[1] "COMTRADE, https://comtrade.un.org/"

$year
[1] "2019"

$countries
[1] "Канада"     "Нидерланды" "США"

$export
   Партнёр 1  Партнёр 2 Экспорт (доллары США)
1     Канада Нидерланды            3905228446
2     Канада        США          336531873909
3 Нидерланды     Канада            4862948109
4 Нидерланды        США           29807484356
5        США     Канада          292338433401
6        США Нидерланды           51225636600

$import
   Партнёр 1  Партнёр 2 Импорт (доллары США)
1     Канада Нидерланды           3515239399
2     Канада        США         229687088046
3 Нидерланды     Канада           2249551077
4 Нидерланды        США          42262861193
5        США     Канада         326628559104
6        США Нидерланды          30883263358

$export_mat
                 Канада  Нидерланды          США
Канада                0  3905228446 336531873909
Нидерланды   4862948109           0  29807484356
США        292338433401 51225636600            0

$import_mat
                 Канада  Нидерланды          США
Канада                0  3515239399 229687088046
Нидерланды   2249551077           0  42262861193
США        326628559104 30883263358            0

**2.6.** Используя созданный список `L_data` и обращаясь только к индексам элементов, выведите на экран:

* третью страну в векторе `countries`;
* объём экспорта из Нидерландов в Канаду из матрицы `export_mat`;
* объём импорта из США в Канаду из матрицы `import_mat`.

In [ ]:
three_country <- L_data$countries[3]
v_export <- L_data$export_mat['Нидерланды', 'Канада']
v_import <- L_data$import_mat['США', 'Канада']

cat('Третья страна в векторе:', three_country, '\n')
cat('Объём экспорта из Нидерландов в Канаду:', v_export, '\n')
cat('Объём импорта из США в Канаду:', v_import)

Третья страна в векторе: США
Объём экспорта из Нидерландов в Канаду: 4862948109
Объём импорта из США в Канаду: 326628559104

**2.7.** Добавьте в конец списка `L_data` элемент без названия, который содержит строку с сегодняшней датой в произвольном формате.

In [ ]:
L_data[[length(L_data) + 1]] <- Sys.Date()

print(L_data)

$source
[1] "COMTRADE, https://comtrade.un.org/"

$year
[1] "2019"

$countries
[1] "Канада"     "Нидерланды" "США"

$export
   Партнёр 1  Партнёр 2 Экспорт (доллары США)
1     Канада Нидерланды            3905228446
2     Канада        США          336531873909
3 Нидерланды     Канада            4862948109
4 Нидерланды        США           29807484356
5        США     Канада          292338433401
6        США Нидерланды           51225636600

$import
   Партнёр 1  Партнёр 2 Импорт (доллары США)
1     Канада Нидерланды           3515239399
2     Канада        США         229687088046
3 Нидерланды     Канада           2249551077
4 Нидерланды        США          42262861193
5        США     Канада         326628559104
6        США Нидерланды          30883263358

$export_mat
                 Канада  Нидерланды          США
Канада                0  3905228446 336531873909
Нидерланды   4862948109           0  29807484356
США        292338433401 51225636600            0

$import_mat
                 Канада  Нидерланды          США
Канада                0  3515239399 229687088046
Нидерланды   2249551077           0  42262861193
США        326628559104 30883263358            0

[[8]]
[1] "2026-04-22"

#Практическая работа 3

## Задача 1

В переменной `belki` сохранено число очков у команды «Белки», а в переменной `strelki` сохранено число очков у команды «Стрелки» (создайте переменные и присвойте им значения по своему усмотрению).

In [ ]:
belki <- c(3,4,6,8,12,15,20,50)
strelki <- c(5,4,12,8,14,15,23,24)

Напишите код, который сравнивает значения переменных, а также:

* если число очков у первой команды больше, чем у второй, выводит на экран сообщение «Победила команда БЕЛКИ!»;

* если число очков у второй команды больше, чем у первой, выводит на экран сообщение «Победила команда СТРЕЛКИ!»;

* если обе команды набрали одинаковое число очков, выводится сообщение «Победила дружба!»

In [ ]:
res1 <- belki == strelki
print(res1)

if (sum(belki) > sum(strelki)){
  print('Победила команда БЕЛКИ!')
} else if (sum(belki) < sum(strelki)){
  print('Победила команда СТРЕЛКИ!')
} else{
  print('Победила дружба!')
}

[1] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE FALSE
[1] "Победила команда БЕЛКИ!"

## Задача 2

Дан вектор со значениями температуры воздуха 10 дней февраля:

In [ ]:
temp <- c(-8, -5, 0, 2, -6, -9, -8, -12, -11, -7)

Нормальная температура в феврале лежит в пределах от $-9,8$ до $-3,7^\circ$С.

Напишите код, который выводит на экран температуру воздуха (каждый элемент вектора `temp`) и комментарий к нему:

* если температура выше нормы, то «Температура выше нормы»;
* если температура ниже нормы, то «Температура ниже нормы»;
* если температура в норме, то «Температура в норме».

In [ ]:
for (i in temp) {
  if (i > -3.7) {
    cat(i, 'Температура выше нормы\n')
  } else if (i < -9.8) {
    cat(i, 'Температура ниже нормы\n')
  } else {
    cat(i, 'Температура в норме\n')
  }
}

-8 Температура в норме
-5 Температура в норме
0 Температура выше нормы
2 Температура выше нормы
-6 Температура в норме
-9 Температура в норме
-8 Температура в норме
-12 Температура ниже нормы
-11 Температура ниже нормы
-7 Температура в норме

## Задача 3

Напишите функцию `progress()`, которая:

* принимает на вход два числа: число сданных домашних заданий и общее число домашних заданий;
* возвращает процент выполненных домашних заданий, округлённый до второго знака после запятой.

In [ ]:
progress <- function(){
  sdan <- as.integer(readline('Число сданных домашних заданий: '))
  k <- as.integer(readline('Общее число домашних заданий: '))
  res <- round((sdan / k) * 100, 2)
  res
}

progress()

Число сданных домашних заданий: 23
Общее число домашних заданий: 14

[1] 164.29

## Задача 4

Напишите функцию `assessment()`, которая:

* принимает на вход вектор прибыли (может содержать как положительные, так и отрицательные значения);
* возвращает вектор такой же длины, что и вектор на входе, из 0 и 1, где 0 соответствует отрицательным и нулевым значениям прибыли, а 1 — положительным значениям прибыли.

В этой задаче необходимо использовать цикл `for`.

**Пример**

На входе: `c(-100, 150, 3500, 720, 0, -350)`.

На выходе: `c(0, 1, 1, 1, 1, 0, 0)`.

In [ ]:
assessment <- function(v){
  for (i in 1:length(v)){
    if (v[i] <= 0){
      v[i] <- 0
    } else{
      v[i] <- 1
    }
  }
  print(v)
}

assessment(c(-100, 150, 3500, 720, 0, -350))

[1] 0 1 1 1 0 0

## Задача 5

Решите предыдущую задачу без использования цикла, но с использованием функции `ifelse()`.
**Подсказка.** Запросите *help* по этой функции и посмотрите, как она работает.

In [ ]:
help(ifelse)

In [ ]:
assessment <- function(v) {
  result <- ifelse(v > 0, 1, 0)
  result
}

print(assessment(c(-100, 150, 3500, 720, 0, -350)))

[1] 0 1 1 1 0 0

## Задача 6
Дан список с адресами (для простоты в списке только улицы):

In [ ]:
addrs <- list("Адрес: улица Высокая, дом 5",
            "Адрес: ул. Речников, дом 10",
		"Адрес: Ул. Педагогическая, дом 12",
		"Адрес: Улица Новая Басманная, дом 9")

Используя функции для работы со строками и функции для векторизованных операций, получите список `addrs_new` со строками такого вида (на примере первого адреса):

```
"Ул. Высокая, дом 5"
```

In [ ]:
zad6 <- function(adres){
  zres1 <- trimws(strsplit(adres, ':')[[1]][2])
  zres2 <- gsub('ица', '.', zres1)
  zres3 <- gsub('ул', 'Ул', zres2)
  zres3
}

addrs_new <- lapply(addrs, zad6)
print(addrs_new)

[[1]]
[1] "Ул. Высокая, дом 5"

[[2]]
[1] "Ул. Речников, дом 10"

[[3]]
[1] "Ул. Педагогическая, дом 12"

[[4]]
[1] "Ул. Новая Басманная, дом 9"

## Задача 7
Напишите функцию `my_median()`, которая принимает на вход числовой вектор и возвращает его медиану. Использовать готовые функции R для нахождения медианы и прочих характеристик, например `median()`, `summary()`, `fivenum()`, нельзя.

Медиана выборки (набора чисел) — такое значение, которое 50% значений выборки не превышают.

Существуют различные алгоритмы вычисления медианы, в этом задании предлагается следующий:

1. Упорядочить вектор по возрастанию.
2. Если число элементов нечётное, то медиана — элемент с индексом `(n+1)/2`, где `n` — длина вектора. Если число элементов чётное, то медиана — среднее арифметическое элементов с индексами `n/2` и `n/2 + 1`.

**Пример 1.** Вектор `c(3, 4, 9, 8, 2)`, медиана 4.

**Пример 2.** Вектор `c(6, 7, 2, 0, 9, 3)`, медиана 4,5.

**Подсказка.** Для проверки чётности числа можно использовать оператор %%, который вычисляет остаток от деления одного числа на другое:

```{r}
5 %% 2
```

In [ ]:
my_median <- function(x) {
  sorted_x <- sort(x)
  n <- length(sorted_x)
  if (n %% 2 == 1) {
    median_value <- sorted_x[(n + 1) / 2]
  } else {
    median_value <- (sorted_x[n / 2] + sorted_x[n / 2 + 1]) / 2
  }
  return(median_value)
}

print(my_median(c(3, 4, 9, 8, 2)))
print(my_median(c(6, 7, 2, 0, 9, 3)))

[1] 4
[1] 4.5

#Практическая работа 4

##Задача 1
Напишите функцию check_id(), которая:

Принимает на вход название рабочей папки или путь к ней, делает указанную папку рабочей.
Открывает все CSV-файлы в рабочей папке. Считайте, что в папке также могут быть файлы других форматов.
Проверяет, есть ли среди столбцов столбец с названием ID.
Создаёт датафрейм с двумя столбцами:
filename: название файла в рабочей папке;
type: наличие столбца ID в файле в рабочей папке (0 — нет, 1 — есть).
Выгружает в файл info.xlsx датафрейм с полученной в пункте выше информацией.
Подсказка: чтобы проверить, заканчивается ли название файла на определённое расширение, например на .csv, можно воспользоваться базовой функцией для строк endsWith().

In [ ]:
library(readxl)
library(writexl)


check_id <- function(directory){
  check_file <- setwd(directory)
  results <- data.frame()
  for (name_file in list.files()){
    if (endsWith(name_file, '.csv')){
      open_file <- read.csv(name_file)
      check_id <- ifelse("ID" %in% colnames(open_file), 1, 0)
      results <- rbind(results, data.frame(filename = name_file, type = check_id))
    }
  }
  write_xlsx(results, 'info.xlsx')
}


print(check_id("C:/Users/alimb/test"))

ERROR: Error in library(writexl): there is no package called ‘writexl’

#Практическая работа 5

## Описание данных

В этом задании вам предлагается поработать с файлом `flats.csv`, который содержит данные по ценам на квартиры в Москве.


Показатели в файле:

* `price`: цена квартиры, в тысячах долларов;
* `totsp`: общая площадь квартиры, в квадратных метрах;
* `livesp`: жилая площадь квартиры, в квадратных метрах;
* `kitsp`: площадь кухни, в квадратных метрах;
* `dist`: расстояние от центра, в километрах;
* `metrdist`: расстояние до метро, в минутах;
* `walk`: шаговая доступность до метро (1 — пешком до метро, 0 — на транспорте);
* `brick`: материал дома (1 — кирпичный, монолит ж/б, 0 — другой);
* `floor`: этаж (1 — этаж кроме первого и последнего, 0 — иначе).

Оригинальное описание файла можно прочитать на [странице](https://www.kaggle.com/hugoncosta/price-of-flats-in-moscow) датафрейма на платформе Kaggle.

##Задача 1

Загрузите данные из файла flats.csv и сохраните их в датафрейм flats. Посмотрите на датафрейм — откройте его в отдельном окне RStudio.

In [ ]:
flats <- read.csv('/flats.csv')

##Задача 2

Выведите на экран первые и последние строки в датафрейме. Выведите информацию о типах столбцов в таблице («структуру» датафрейма). Проверьте, чтобы все столбцы с числовыми данными считались как числовые, а не текстовые.

In [ ]:
print(head(flats))
print(tail(flats))
print(str(flats))

  price totsp livesp kitsp dist metrdist walk brick floor
1   730   134    102    10  9.0       10    1     1     1
2   477   119     93    15  9.0        1    1     0     1
3   350    80     44    14 10.5       10    1     1     0
4   410   102     75    10  6.5        5    1     1     1
5    50    63     47     7 12.0       20    0     1     0
6   340    83     49    19  9.0        5    1     1     1
     price totsp livesp kitsp dist metrdist walk brick floor
2035   110    75     45    10 12.7       10    1     0     1
2036   117    76     43    10 12.0        5    1     0     1
2037    91    60     44     6 14.5        7    1     0     1
2038    94    65     40     8 14.5       15    1     0     1
2039   110    74     44    10 13.0        7    1     0     1
2040    90    61     43     6 14.5       10    1     0     1
'data.frame':	2040 obs. of  9 variables:
 $ price   : int  730 477 350 410 50 340 285 470 135 470 ...
 $ totsp   : int  134 119 80 102 63 83 90 146 105 120 ...
 $ livesp  : int  102 93 44 75 47 49 61 86 58 75 ...
 $ kitsp   : num  10 15 14 10 7 19 6 16 21 18 ...
 $ dist    : num  9 9 10.5 6.5 12 9 14.5 14.5 13.5 9 ...
 $ metrdist: int  10 1 10 5 20 5 10 5 15 10 ...
 $ walk    : int  1 1 1 1 0 1 1 1 1 1 ...
 $ brick   : int  1 0 1 1 1 1 0 1 1 1 ...
 $ floor   : int  1 1 0 1 0 1 1 1 1 1 ...
NULL

##Задача 3

Выведите на экран сводные характеристики всех столбцов в датафрейме — описательные статистики. Ответьте на вопросы: наблюдаются ли серьёзные отличия в медианных и средних значениях показателей (один из признаков наличия аномальных наблюдений или выбросов)? Насколько велик разброс значений цен на квартиры, если мы сравним минимальное и максимальное значение? Есть ли в каком-нибудь показателе с содержательной точки зрения нетипичные значения (отрицательные цены и прочее)?

In [ ]:
print(summary(flats))

# 1)Наблюдаются ли серьёзные отличия в медианных и средних значениях показателей (один из признаков наличия аномальных наблюдений или выбросов?
#Cреднее значение для цены квартиры (127.5) больше медианного (115.0), что может указывать на наличие аномально высоких значений (выбросов).
#2) Насколько велик разброс значений цен на квартиры, если мы сравним минимальное и максимальное значение? Цена за квартиру варьируется от 50 тысяч долларов
#до 730 тясяч долларов, что в 14,6 раз больше минимальной цены, поэтому разброс цен за квартиру веклик.
#3)  Есть ли в каком-нибудь показателе с содержательной точки зрения нетипичные значения (отрицательные цены и прочее)? Нет, нетипичных значений не наблюдается.

     price           totsp            livesp           kitsp
 Min.   : 50.0   Min.   : 44.00   Min.   : 28.00   Min.   : 5.000
 1st Qu.: 95.0   1st Qu.: 62.00   1st Qu.: 42.00   1st Qu.: 7.000
 Median :115.0   Median : 73.50   Median : 45.00   Median : 9.000
 Mean   :127.5   Mean   : 73.08   Mean   : 46.34   Mean   : 8.899
 3rd Qu.:142.0   3rd Qu.: 79.00   3rd Qu.: 50.00   3rd Qu.:10.000
 Max.   :730.0   Max.   :192.00   Max.   :102.00   Max.   :25.000
      dist          metrdist           walk            brick
 Min.   : 3.00   Min.   : 1.000   Min.   :0.0000   Min.   :0.000
 1st Qu.: 9.00   1st Qu.: 5.000   1st Qu.:0.0000   1st Qu.:0.000
 Median :12.00   Median : 7.000   Median :1.0000   Median :0.000
 Mean   :11.02   Mean   : 8.117   Mean   :0.6858   Mean   :0.323
 3rd Qu.:13.50   3rd Qu.:10.000   3rd Qu.:1.0000   3rd Qu.:1.000
 Max.   :17.00   Max.   :20.000   Max.   :1.0000   Max.   :1.000
     floor
 Min.   :0.0000
 1st Qu.:1.0000
 Median :1.0000
 Mean   :0.7907
 3rd Qu.:1.0000
 Max.   :1.0000

##Задача 4

Используя базовые средства R, добавьте в датафрейм flats столбец priceru, содержащий значения цен на квартиры в тысячах рублей. Считайте, что один доллар равен примерно 78 рублям.

In [ ]:
flats$priceru <- flats$price * 78
print(flats)

     price totsp livesp kitsp dist metrdist walk brick floor priceru
1      730   134    102  10.0  9.0       10    1     1     1   56940
2      477   119     93  15.0  9.0        1    1     0     1   37206
3      350    80     44  14.0 10.5       10    1     1     0   27300
4      410   102     75  10.0  6.5        5    1     1     1   31980
5       50    63     47   7.0 12.0       20    0     1     0    3900
6      340    83     49  19.0  9.0        5    1     1     1   26520
7      285    90     61   6.0 14.5       10    1     0     1   22230
8      470   146     86  16.0 14.5        5    1     1     1   36660
9      135   105     58  21.0 13.5       15    1     1     1   10530
10     470   120     75  18.0  9.0       10    1     1     1   36660
11     450   125     80  20.0  9.0        3    1     0     1   35100
12      87    90     57  13.0 14.5       15    1     1     1    6786
13     142   125     66  19.0 10.5       10    1     0     1   11076
14      73    77     45  10.0  5.0        7    1     0     1    5694
15     126   119     67  17.0 15.5       10    1     0     0    9828
16     350    90     62  12.0 10.5        5    0     0     1   27300
17     270    82     49  13.0  8.0       15    1     0     1   21060
18     420   102     70  20.0  3.0        2    1     1     1   32760
19      52    86     46   9.0 12.0       10    0     0     1    4056
20     530   150     80  15.0  7.5        7    1     1     1   41340
21     127   119     68  15.0 15.5       10    1     0     1    9906
22     170    53     33   9.0  3.0       10    1     1     1   13260
23     116    77     45  18.0  6.0        7    0     0     1    9048
24      84    74     41  12.0  7.0        3    1     0     1    6552
25     350   113     85  20.0  9.0       10    1     0     1   27300
26     130   109     51  16.0 13.5       10    0     1     1   10140
27     223    63     38   7.0  7.5        3    1     1     1   17394
28     285    90     57   7.0  3.0        3    1     0     1   22230
29     175   112     78  16.0  7.0       10    1     1     1   13650
30     190   106     58  24.0  9.0        5    0     0     1   14820
31      56    68     43   7.0 13.5       10    0     1     1    4368
32     310   100     62  17.0  4.5       15    1     0     1   24180
33     100    77     50   6.0  3.5        3    1     1     1    7800
34     135    65     39   7.0 12.0       15    0     0     0   10530
35     260   107     58  14.0 13.0        1    1     0     1   20280
36     125    93     66   9.0  6.0        5    1     1     0    9750
37     220   148     85  14.0 14.5        7    0     1     1   17160
38     280   108     65  14.0 14.5       15    1     1     1   21840
39     299   100     65  11.0  9.0       10    1     0     1   23322
40     147   111     65  16.0 14.5        6    0     1     1   11466
41     174   130     71  16.0 14.5        4    0     0     1   13572
42      92    85     53  10.0 12.0       15    1     1     0    7176
43     207   134     77  21.0 15.5        5    1     0     1   16146
44     360   103     80  14.0  3.0        3    1     1     1   28080
45     260    80     46  12.0  9.0        2    1     1     1   20280
46     160    57     42   8.0  3.5        5    1     1     1   12480
47     250   100     50  15.0 12.7        5    1     0     1   19500
48     352   108     81  16.0  4.5       10    1     1     1   27456
49     210    71     45  15.0  9.0        1    1     1     1   16380
50     170    98     73  12.0  6.0        1    1     1     0   13260
51     210    71     45   6.0  9.0        1    1     1     1   16380
52      99    79     62   6.0 17.0        2    1     1     0    7722
53     260    70     45   8.0  8.0        7    1     1     0   20280
54     340   121     72  13.0 12.5        3    1     1     1   26520
55      82    62     32   7.0  6.0        5    1     1     0    6396
56     215    67     42   9.0  7.5        3    1     1     1   16770
57      72    64     43   7.0  6.0        7    1     0     1    5616
58     252   132     74  23.0 12.5        3    1     1     0   19656
59     199   127     62  20.0 13.5       10    0     1     1   15522
60     371   120     59  15.0  7.0       10    0     0     1   28938
61     371   120     59  15.0  7.0       10    0     0     1   28938
62     250    74     56   8.0  4.5        7    1     1     1   19500
63     151   111     64  16.0 14.5       10    0     1     1   11778
64     160   119     68  10.0 11.0        7    1     1     0   12480
65     190    73     41  11.0  3.5        1    1     1     1   14820
66     180    71     42   8.0  7.0       15    0     0     1   14040
67     299    99     65  11.0  9.0       10    1     1     1   23322
68     250    74     47  10.0  3.0        5    1     1     0   19500
69     200    85     54  14.0 14.5       15    1     0     1   15600
70     210    94     59  11.0 12.7        2    1     1     1   16380
71     132    94     60  11.0  6.5        3    1     0     0   10296
72     150   112     64  16.0 14.5        5    0     0     1   11700
73     120    56     42   6.0 12.0        5    1     1     1    9360
74     330   104     60  11.0 10.5        7    0     1     1   25740
75     460   153     84  18.0  9.0        5    1     1     1   35880
76     370   111     60  13.0  8.0        5    1     1     1   28860
77     380   130     72  15.0  7.0        5    0     0     1   29640
78     126    84     56   9.0  3.5        4    1     1     1    9828
79     299   100     75  12.0  6.5        5    1     1     1   23322
80     150    92     69   8.0  4.5       10    1     1     1   11700
81      79    65     45   7.0  6.0        7    1     0     1    6162
82     120    66     40  19.0  7.5       10    1     1     1    9360
83     230   103     51  14.0 14.5       15    1     1     1   17940
84     210    80     42  20.0  8.0        5    1     0     1   16380
85     160    68     44   8.0 17.0        5    1     0     1   12480
86     230    95     64  10.0 10.5       15    1     1     1   17940
87      90    64     39   9.0  6.0        5    0     1     1    7020
88     150   108     56  15.0 11.0        5    1     1     1   11700
89     200    90     60  10.0 12.0       10    1     1     1   15600
90     190    85     53  12.0 12.0        3    1     0     0   14820
91      96    76     53   8.0  6.0       10    0     1     1    7488
92     130    56     40   5.0  3.5       10    1     1     0   10140
93     185    66     44   6.0  9.0        3    1     1     0   14430
94     240    81     54   8.0  9.0        3    1     1     0   18720
95     150    54     39   6.0  7.0        3    1     1     1   11700
96     135    84     55  11.0  3.0       15    1     1     1   10530
97     110    85     54  10.0  6.0       10    0     1     1    8580
98     130    56     42   7.0 14.5        3    1     1     1   10140
99     120    75     48  11.0  3.0       15    1     1     1    9360
100    450   145     82  14.0  4.5        3    1     1     1   35100
101    180    83     53   8.0 12.0        5    1     1     1   14040
102    170    92     62  18.0  6.0        7    1     1     1   13260
103    315   118     54  12.0  3.5        2    1     1     1   24570
104    160    92     69  14.0  4.5       10    1     1     1   12480
105    245    80     49  10.0  3.0       10    1     1     0   19110
106    152   108     56  15.0 11.0        5    1     1     1   11856
107    113    91     52   9.0  6.5       10    1     1     1    8814
108    451   156     80  20.0 10.5        5    0     1     1   35178
109     73    53     34   6.0  7.5        3    1     1     0    5694
110    309   107     72  17.0 10.5        1    1     1     1   24102
111    245    83     48  12.0  7.5       10    1     1     1   19110
112    170    82     52  20.0  5.0        1    1     0     1   13260
113     75    79     47   8.0 17.0       10    0     0     1    5850
114    145    63     41   8.0  3.5        3    1     0     1   11310
115    130    96     57   9.0  7.5        5    0     1     1   10140
116    270    97     56  18.0  8.0       10    1     1     1   21060
117    109    79     45  13.0 14.5        5    0     1     1    8502
118    371   128     70  18.0  7.0        5    0     0     1   28938
119    125    66     40  10.0 12.0       20    1     0     1    9750
120    212   119     70  17.0  9.0        5    0     1     1   16536
121    115    86     67  13.0 13.5       15    0     0     1    8970
122    120    77     51  12.0  4.5        7    0     1     1    9360
123    132    88     63   8.0  8.0        5    1     1     1   10296
124    235    92     52  15.0  3.5        3    1     0     1   18330
125    250    78     47  10.0 10.5        7    1     0     1   19500
126    171    96     50  18.0  7.0        5    1     0     1   13338
127    120   100     63   9.0 13.0        7    0     0     1    9360
128    110    51     34   6.0  3.5        7    1     0     1    8580
129     90    72     53  10.0 11.5        5    0     1     1    7020
130    135    75     43  11.0 12.7       15    1     0     1   10530
131    227   134     70  16.0  9.0        5    1     0     1   17706
132    215    76     55   8.0  7.5        2    1     1     1   16770
133    210    72     49   7.0  7.5        5    1     1     1   16380
134    200    77     46  10.0  3.0       15    1     1     1   15600
135     85    65     43   5.0  7.5        5    1     1     1    6630
136    125    63     43   6.0 17.0        5    1     1     1    9750
137    220    81     46  13.0  9.0        7    1     0     1   17160
138    114    83     46  12.0  7.0       10    1     0     1    8892
139    210    80     49  10.0 12.5        5    1     1     1   16380
140    225   101     65  15.0 10.5       20    1     1     1   17550
141    109    79     45  13.0 14.5        7    0     1     1    8502
142    201    82     55   9.0 13.5        7    1     0     1   15678
143    100    77     52   9.0 10.5       15    0     1     1    7800
144    260   135     75  20.0 12.5        3    1     1     0   20280
145    130    86     54  13.0  6.0       10    1     0     1   10140
146    193    78     55   8.0  7.5       10    1     0     1   15054
147    196    78     46  10.0 14.5        5    1     0     1   15288
148    115    57     38   8.0 12.0        5    1     0     1    8970
149    120    76     49   9.0  3.0       10    1     1     0    9360
150    115    77     51   7.0  5.0        5    1     1     0    8970
151     97    80     48   8.0 13.0        5    0     1     1    7566
152    230    80     46  13.0  5.0        4    1     1     1   17940
153    167   113     64  13.0 14.5        5    0     1     1   13026
154    160   114     67  15.0 14.5       10    0     0     1   12480
155    105    72     52   8.0  6.0       15    0     1     1    8190
156    200   121     71  12.0 10.0        3    1     0     1   15600
157    200    72     46   9.0  9.0       10    1     1     1   15600
158    197    70     46   7.0  4.5        3    1     1     1   15366
159    140    56     40   5.0  9.0        5    1     1     0   10920
160    149    77     45  10.0 13.0        2    1     0     1   11622
161    160    84     50   9.0 12.7        1    1     0     1   12480
162    165    99     70   9.0  7.5        7    0     1     1   12870
163     95    63     42   8.0  3.5        5    1     1     1    7410
164    170    81     60  13.0 13.0        5    1     0     1   13260
165    116    75     51   9.0  3.5        5    0     1     0    9048
166    140    99     51  12.0 10.5        1    1     0     0   10920
167    153    80     40  25.0 10.5       10    0     0     1   11934
168    163   115     66  15.0 13.5       10    0     0     1   12714
169    226    82     52  10.0  3.0        3    1     0     1   17628
170    114    93     51  12.0 10.0        7    1     0     0    8892
171    129    99     55  11.0 10.5       15    1     0     0   10062
172    125    83     53  10.0  5.0       12    1     0     0    9750
173    180    79     45  10.0  8.0       15    1     0     1   14040
174    145    74     45  10.0 15.5       15    1     0     1   11310
175    141   113     58  13.0 13.5       10    0     0     1   10998
176     78    63     47   6.0 13.5        5    0     1     1    6084
177    185    78     53   8.0  7.5       15    1     1     1   14430
178    225    80     56   9.0  9.0        5    1     1     1   17550
179    170    86     56  10.0 12.0        2    1     0     1   13260
180    147    77     44  10.0 13.0        2    1     0     1   11466
181    220    83     53   9.0  4.5        5    1     0     0   17160
182    179    65     45   8.0  9.0        5    1     1     1   13962
183    265   100     56  14.0  7.0       10    0     0     1   20670
184    245    85     54  12.0  9.0        7    1     1     1   19110
185     88    72     51   9.0 11.5       10    0     1     1    6864
186    177    74     45   8.0  5.0       15    1     1     1   13806
187    155    60     40  11.0  7.5        5    1     1     1   12090
188    105    75     50   8.0  6.5       15    1     1     0    8190
189    199    70     46   8.0  7.5        7    1     1     1   15522
190    230   109     58  18.0 12.7        2    1     0     1   17940
191    220   100     49  13.0 14.5       10    1     1     1   17160
192    100    83     53  10.0 12.0       15    0     0     0    7800
193    170    65     45   7.0  7.5        2    1     1     1   13260
194    125    81     56   9.0  6.0        5    1     1     0    9750
195    200    71     46   8.0  4.5        5    1     1     0   15600
196    101    62     43   6.0 12.0       15    1     0     1    7878
197     78    64     39   8.0  7.0       10    0     0     1    6084
198     72    60     42   6.0 11.5       10    0     1     0    5616
199    110    77     46  10.0  6.0       10    0     0     1    8580
200     98    74     46  11.0 12.5       10    0     1     0    7644
201    110    86     53   9.0 10.5        5    0     0     0    8580
202    220    77     49  10.0  7.5        5    1     1     1   17160
203    155    64     36   8.0  8.0        7    1     1     0   12090
204    155    60     40   8.0  7.5        5    1     1     1   12090
205    194   106     60  17.0  9.0        5    0     1     1   15132
206    142    83     45  10.0 12.7       15    1     0     1   11076
207    170    86     59  10.0 17.0       10    0     1     1   13260
208    103    78     54  11.0 12.0       15    1     1     0    8034
209    159   109     64  13.0 14.5       10    0     1     1   12402
210     95    74     45   8.0 14.5        5    0     1     0    7410
211    115    77     50   9.0  3.5        7    1     0     0    8970
212    175    81     47  10.0 14.5       10    0     1     1   13650
213    112    79     45   8.0 11.5        2    1     1     1    8736
214    175    79     47   9.0 14.5        7    1     1     1   13650
215    200    78     50   7.0  8.0       10    1     1     1   15600
216     89    79     52  10.0 15.5       10    1     0     1    6942
217    118    71     41   8.0 12.0       15    0     0     1    9204
218     93    78     46  10.0 12.0       15    0     0     1    7254
219    160    77     45  10.0 12.0       15    1     0     1   12480
220    132    84     52  11.0 12.7       20    1     0     1   10296
221     85    59     44   6.0  7.0        1    1     0     1    6630
222    150    75     51   8.0 12.0       15    1     0     0   11700
223    250    92     57  11.0  9.0        3    1     1     1   19500
224     98    79     48  10.0 12.0       10    1     1     1    7644
225    122    93     52  14.0 13.5       10    1     0     1    9516
226    130    82     37  12.0  6.0       10    1     0     1   10140
227    138    95     63   9.0 10.0       10    1     0     1   10764
228    225    80     53   9.0  7.0        5    1     1     1   17550
229     99    72     50   9.0  7.5       10    0     1     1    7722
230    230    92     60  14.0  9.0       10    1     0     0   17940
231    100    83     48  10.0 12.0       15    0     0     0    7800
232     81    53     34   6.0 13.0       15    1     0     0    6318
233     96    60     43   6.0 12.0       15    1     0     1    7488
234    208   115     70  14.0 10.0        3    1     1     1   16224
235    170    68     39  10.0  4.5       10    1     1     0   13260
236     70    58     41   6.0 14.5       10    0     1     1    5460
237    166    77     45  11.0 10.5       15    1     1     1   12948
238    150    78     44  10.0 14.5       15    1     0     1   11700
239    190    72     46  10.0  9.0        5    1     1     1   14820
240    167    74     43  10.0 14.5        5    1     0     1   13026
241    165    65     45   9.0  9.0       10    1     1     1   12870
242    165    65     45   9.0  9.0       10    1     1     1   12870
243     84    76     45  10.0 17.0       10    1     0     1    6552
244    130    78     53  13.0  3.5       10    1     1     1   10140
245    185    80     53   9.0  7.5       15    1     1     1   14430
246    180    71     47   7.0  7.5       10    1     1     1   14040
247    220   103     49  13.0 14.5       10    1     1     1   17160
248     78    55     37   6.0 11.5        2    1     1     1    6084
249     78    55     37   6.0 11.5        2    1     1     1    6084
250    165    90     65   8.0  6.0        2    1     1     1   12870
251    159   107     64  13.0 14.5       10    0     1     1   12402
252    200   122     68  12.0 10.0        5    1     0     1   15600
253    123    58     40   7.0 13.5        5    0     1     1    9594
254    164    72     48   7.0  3.5        5    1     1     1   12792
255    118    77     43  11.0  7.0        5    0     0     1    9204
256    185    76     43  10.0  8.0       10    1     0     1   14430
257    185    68     47   8.0  4.5        5    1     1     1   14430
258    125    77     51   8.0  6.0        3    1     1     1    9750
259    160    68     40   9.0  9.0       10    1     1     1   12480
260    104    84     52  11.0 13.0        5    0     0     1    8112
261    158    64     44   9.0  7.0        3    1     0     1   12324
262    138    86     54  10.0  6.0        5    0     1     1   10764
263    116    77     45  10.0  6.0        7    0     0     1    9048
264    240    92     57  12.0  6.5       12    1     1     1   18720
265    129    69     42   9.0 14.5       15    1     0     1   10062
266     81    56     41   5.0  6.0       10    0     1     1    6318
267    115    77     50   9.0  6.0       10    1     1     1    8970
268    149    92     50  14.0 10.0        7    1     1     1   11622
269    132    96     56  12.0 10.5        7    0     0     1   10296
270    154    95     51  11.0  6.5        3    1     1     1   12012
271    145    74     45  11.0 17.0       10    0     0     1   11310
272    127    92     50  11.0  6.5       10    1     0     1    9906
273    167    74     43  10.0 14.5        7    1     0     1   13026
274    130    84     54   8.0  6.5       15    1     1     1   10140
275     92    82     48   8.0 13.0       12    0     0     1    7176
276    111    75     42  11.0 14.5        3    0     1     1    8658
277    185    80     45  13.0 12.0        5    0     0     1   14430
278    165    96     58  14.0  7.0        5    0     0     1   12870
279    340   125     70  18.0  7.0       10    0     1     1   26520
280    210    79     53   8.0  7.0        5    1     1     1   16380
281    123    81     48   9.0 12.0       20    0     0     0    9594
282    230    85     58  13.0  3.0        5    1     0     1   17940
283    100    58     30   6.0 17.0        1    1     0     1    7800
284    105    78     50   8.0  9.0       10    1     1     0    8190
285    155    73     49   9.0 10.5       15    1     1     1   12090
286    155    73     49   9.0 10.5       15    1     1     1   12090
287    140    75     40  11.0 13.0        5    0     0     1   10920
288     97    76     45  10.0 12.0       10    1     1     1    7566

##Задача 5

Сохраните максимальное значение цены на квартиру в тысячах рублей в переменную pricemax. Используя фильтрацию строк, выясните, какими характеристиками обладает самая дорогая (согласно имеющимся данным) квартира в Москве.

In [ ]:
pricemax <- max(flats$priceru)
print(pricemax)

over_price_info <- flats[flats$priceru == pricemax, ]
print(over_price_info)

[1] 56940
  price totsp livesp kitsp dist metrdist walk brick floor priceru
1   730   134    102    10    9       10    1     1     1   56940

##Задача 6

Сохраните минимальное значение цены на квартиру в тысячах рублей в переменную pricemin. Используя фильтрацию строк, выясните, какими характеристиками обладает самая дешёвая (согласно имеющимся данным) квартира в Москве.

In [ ]:
pricemin <- min(flats$priceru)
print(pricemin)

min_price_info <- flats[flats$priceru == pricemin, ]
print(min_price_info)

[1] 3900
  price totsp livesp kitsp dist metrdist walk brick floor priceru
5    50    63     47     7   12       20    0     1     0    3900

##Задача 7

Выберите из датафрейма flats строки, соответствующие квартирам, которые находятся в шаговой доступности от метро и с жилой площадью выше средней. Сохраните их в датафрейм flats1.

In [ ]:
flats1 <- flats[flats$walk == 1 & flats$livesp > median(flats$livesp), ]
print(flats1)

     price totsp livesp kitsp dist metrdist walk brick floor priceru
1      730   134    102  10.0  9.0       10    1     1     1   56940
2      477   119     93  15.0  9.0        1    1     0     1   37206
4      410   102     75  10.0  6.5        5    1     1     1   31980
6      340    83     49  19.0  9.0        5    1     1     1   26520
7      285    90     61   6.0 14.5       10    1     0     1   22230
8      470   146     86  16.0 14.5        5    1     1     1   36660
9      135   105     58  21.0 13.5       15    1     1     1   10530
10     470   120     75  18.0  9.0       10    1     1     1   36660
11     450   125     80  20.0  9.0        3    1     0     1   35100
12      87    90     57  13.0 14.5       15    1     1     1    6786
13     142   125     66  19.0 10.5       10    1     0     1   11076
15     126   119     67  17.0 15.5       10    1     0     0    9828
17     270    82     49  13.0  8.0       15    1     0     1   21060
18     420   102     70  20.0  3.0        2    1     1     1   32760
20     530   150     80  15.0  7.5        7    1     1     1   41340
21     127   119     68  15.0 15.5       10    1     0     1    9906
25     350   113     85  20.0  9.0       10    1     0     1   27300
28     285    90     57   7.0  3.0        3    1     0     1   22230
29     175   112     78  16.0  7.0       10    1     1     1   13650
32     310   100     62  17.0  4.5       15    1     0     1   24180
33     100    77     50   6.0  3.5        3    1     1     1    7800
35     260   107     58  14.0 13.0        1    1     0     1   20280
36     125    93     66   9.0  6.0        5    1     1     0    9750
38     280   108     65  14.0 14.5       15    1     1     1   21840
39     299   100     65  11.0  9.0       10    1     0     1   23322
42      92    85     53  10.0 12.0       15    1     1     0    7176
43     207   134     77  21.0 15.5        5    1     0     1   16146
44     360   103     80  14.0  3.0        3    1     1     1   28080
45     260    80     46  12.0  9.0        2    1     1     1   20280
47     250   100     50  15.0 12.7        5    1     0     1   19500
48     352   108     81  16.0  4.5       10    1     1     1   27456
50     170    98     73  12.0  6.0        1    1     1     0   13260
52      99    79     62   6.0 17.0        2    1     1     0    7722
54     340   121     72  13.0 12.5        3    1     1     1   26520
58     252   132     74  23.0 12.5        3    1     1     0   19656
62     250    74     56   8.0  4.5        7    1     1     1   19500
64     160   119     68  10.0 11.0        7    1     1     0   12480
67     299    99     65  11.0  9.0       10    1     1     1   23322
68     250    74     47  10.0  3.0        5    1     1     0   19500
69     200    85     54  14.0 14.5       15    1     0     1   15600
70     210    94     59  11.0 12.7        2    1     1     1   16380
71     132    94     60  11.0  6.5        3    1     0     0   10296
75     460   153     84  18.0  9.0        5    1     1     1   35880
76     370   111     60  13.0  8.0        5    1     1     1   28860
78     126    84     56   9.0  3.5        4    1     1     1    9828
79     299   100     75  12.0  6.5        5    1     1     1   23322
80     150    92     69   8.0  4.5       10    1     1     1   11700
83     230   103     51  14.0 14.5       15    1     1     1   17940
86     230    95     64  10.0 10.5       15    1     1     1   17940
88     150   108     56  15.0 11.0        5    1     1     1   11700
89     200    90     60  10.0 12.0       10    1     1     1   15600
90     190    85     53  12.0 12.0        3    1     0     0   14820
94     240    81     54   8.0  9.0        3    1     1     0   18720
96     135    84     55  11.0  3.0       15    1     1     1   10530
99     120    75     48  11.0  3.0       15    1     1     1    9360
100    450   145     82  14.0  4.5        3    1     1     1   35100
101    180    83     53   8.0 12.0        5    1     1     1   14040
102    170    92     62  18.0  6.0        7    1     1     1   13260
103    315   118     54  12.0  3.5        2    1     1     1   24570
104    160    92     69  14.0  4.5       10    1     1     1   12480
105    245    80     49  10.0  3.0       10    1     1     0   19110
106    152   108     56  15.0 11.0        5    1     1     1   11856
107    113    91     52   9.0  6.5       10    1     1     1    8814
110    309   107     72  17.0 10.5        1    1     1     1   24102
111    245    83     48  12.0  7.5       10    1     1     1   19110
112    170    82     52  20.0  5.0        1    1     0     1   13260
116    270    97     56  18.0  8.0       10    1     1     1   21060
123    132    88     63   8.0  8.0        5    1     1     1   10296
124    235    92     52  15.0  3.5        3    1     0     1   18330
125    250    78     47  10.0 10.5        7    1     0     1   19500
126    171    96     50  18.0  7.0        5    1     0     1   13338
131    227   134     70  16.0  9.0        5    1     0     1   17706
132    215    76     55   8.0  7.5        2    1     1     1   16770
133    210    72     49   7.0  7.5        5    1     1     1   16380
134    200    77     46  10.0  3.0       15    1     1     1   15600
137    220    81     46  13.0  9.0        7    1     0     1   17160
138    114    83     46  12.0  7.0       10    1     0     1    8892
139    210    80     49  10.0 12.5        5    1     1     1   16380
140    225   101     65  15.0 10.5       20    1     1     1   17550
142    201    82     55   9.0 13.5        7    1     0     1   15678
144    260   135     75  20.0 12.5        3    1     1     0   20280
145    130    86     54  13.0  6.0       10    1     0     1   10140
146    193    78     55   8.0  7.5       10    1     0     1   15054
147    196    78     46  10.0 14.5        5    1     0     1   15288
149    120    76     49   9.0  3.0       10    1     1     0    9360
150    115    77     51   7.0  5.0        5    1     1     0    8970
152    230    80     46  13.0  5.0        4    1     1     1   17940
156    200   121     71  12.0 10.0        3    1     0     1   15600
157    200    72     46   9.0  9.0       10    1     1     1   15600
158    197    70     46   7.0  4.5        3    1     1     1   15366
161    160    84     50   9.0 12.7        1    1     0     1   12480
164    170    81     60  13.0 13.0        5    1     0     1   13260
166    140    99     51  12.0 10.5        1    1     0     0   10920
169    226    82     52  10.0  3.0        3    1     0     1   17628
170    114    93     51  12.0 10.0        7    1     0     0    8892
171    129    99     55  11.0 10.5       15    1     0     0   10062
172    125    83     53  10.0  5.0       12    1     0     0    9750
177    185    78     53   8.0  7.5       15    1     1     1   14430
178    225    80     56   9.0  9.0        5    1     1     1   17550
179    170    86     56  10.0 12.0        2    1     0     1   13260
181    220    83     53   9.0  4.5        5    1     0     0   17160
184    245    85     54  12.0  9.0        7    1     1     1   19110
188    105    75     50   8.0  6.5       15    1     1     0    8190
189    199    70     46   8.0  7.5        7    1     1     1   15522
190    230   109     58  18.0 12.7        2    1     0     1   17940
191    220   100     49  13.0 14.5       10    1     1     1   17160
194    125    81     56   9.0  6.0        5    1     1     0    9750
195    200    71     46   8.0  4.5        5    1     1     0   15600
202    220    77     49  10.0  7.5        5    1     1     1   17160
208    103    78     54  11.0 12.0       15    1     1     0    8034
211    115    77     50   9.0  3.5        7    1     0     0    8970
214    175    79     47   9.0 14.5        7    1     1     1   13650
215    200    78     50   7.0  8.0       10    1     1     1   15600
216     89    79     52  10.0 15.5       10    1     0     1    6942
220    132    84     52  11.0 12.7       20    1     0     1   10296
222    150    75     51   8.0 12.0       15    1     0     0   11700
223    250    92     57  11.0  9.0        3    1     1     1   19500
224     98    79     48  10.0 12.0       10    1     1     1    7644
225    122    93     52  14.0 13.5       10    1     0     1    9516
227    138    95     63   9.0 10.0       10    1     0     1   10764
228    225    80     53   9.0  7.0        5    1     1     1   17550
230    230    92     60  14.0  9.0       10    1     0     0   17940
234    208   115     70  14.0 10.0        3    1     1     1   16224
239    190    72     46  10.0  9.0        5    1     1     1   14820
244    130    78     53  13.0  3.5       10    1     1     1   10140
245    185    80     53   9.0  7.5       15    1     1     1   14430
246    180    71     47   7.0  7.5       10    1     1     1   14040
247    220   103     49  13.0 14.5       10    1     1     1   17160
250    165    90     65   8.0  6.0        2    1     1     1   12870
252    200   122     68  12.0 10.0        5    1     0     1   15600
254    164    72     48   7.0  3.5        5    1     1     1   12792
257    185    68     47   8.0  4.5        5    1     1     1   14430
258    125    77     51   8.0  6.0        3    1     1     1    9750
264    240    92     57  12.0  6.5       12    1     1     1   18720
267    115    77     50   9.0  6.0       10    1     1     1    8970
268    149    92     50  14.0 10.0        7    1     1     1   11622
270    154    95     51  11.0  6.5        3    1     1     1   12012
272    127    92     50  11.0  6.5       10    1     0     1    9906
274    130    84     54   8.0  6.5       15    1     1     1   10140
280    210    79     53   8.0  7.0        5    1     1     1   16380
282    230    85     58  13.0  3.0        5    1     0     1   17940
284    105    78     50   8.0  9.0       10    1     1     0    8190
285    155    73     49   9.0 10.5       15    1     1     1   12090
286    155    73     49   9.0 10.5       15    1     1     1   12090
293    170    82     52  15.0  5.0        1    1     1     1   13260
296    170    80     48   9.0 14.5        7    1     1     1   13260
298    240   106     71   9.0  9.0       10    1     1     1   18720
305    130    81     56   9.0  6.0        7    1     1     0   10140
306    130    81     56   9.0  6.0        7    1     1     1   10140
307    179    73     47   6.0  3.0       10    1     1     1   13962
309    115    75     47   8.0  6.5       15    1     1     0    8970
310    130    82     54   8.0  3.5       10    1     1     1   10140
312    150    97     63  11.0 10.0        7    1     0     1   11700
313    139    80     48  10.0 10.5       15    1     0     1   10842
317    140    67     46   9.0  8.0       15    1     0     1   10920
323    124    96     52  10.0 13.5        5    1     0     1    9672
325    151   102     70   9.0 10.5       12    1     1     1   11778
334    209    90     57   8.0 10.5        2    1     1     1   16302
336    149    78     48  13.0  4.5        5    1     1     1   11622
339    260   110     56  15.0 12.5        3    1     1     1   20280
346    190    73     54   9.0  3.0       10    1     1     1   14820
350    156    70     48   7.0  9.0        2    1     0     1   12168
353    144    95     62  11.0 10.0       10    1     0     1   11232
355    160    86     51   8.0 12.0        2    1     1     1   12480
357    200   100     66  21.0  9.0       15    1     1     1   15600
360    190    78     46  10.0  8.0       10    1     1     1   14820
364    133    75     52   9.0  3.0       15    1     1     0   10374
365    160   101     51  15.0  7.0        7    1     0     1   12480
367    105    78     54   9.0 11.0       10    1     1     1    8190
368    145    78     50  10.0 12.0        3    1     0     1   11310
376    300   127     66  15.0 12.5        5    1     1     1   23400
378    125    67     46   8.0 12.5       15    1     0     1    9750
381    128    72     53   8.0  3.0       10    1     1     0    9984
384    113    75     51   9.0  7.5       10    1     1     0    8814
388    133    75     48   9.0  3.0       12    1     1     0   10374
389    205    88     59   9.0  9.0       10    1     1     0   15990
398    225    92     48  13.0  9.0        1    1     1     1   17550
401    127    85     46  14.0 12.0        7    1     1     1    9906
402    170    71     47   8.0  7.5       10    1     1     1   13260
406    215    90     61   9.0  9.0        1    1     1     1   16770
408     95    82     48   8.0 13.0       10    1     0     1    7410
410    265   136     88  14.0 10.5       10    1     1     1   20670
411    170    89     51  12.0 12.7        6    1     0     0   13260
415    112    72     51   8.0  6.5        5    1     1     0    8736
416    112    72     51   8.0  6.5        5    1     1     1    8736
417    143    85     52   9.0  5.0        8    1     1     1   11154
420    140    87     57   7.0 10.5        3    1     1     1   10920
422    168   105     56  12.0  9.0        5    1     0     1   13104
426    145    69     47   7.0  3.5       10    1     1     1   11310
432    180    73     46  10.0  7.5        3    1     1     1   14040
433    125    79     56   8.0  7.5       10    1     1     1    9750
434    140    85     50   8.0  6.5        2    1     1     1   10920
437    155    80     46  13.0 12.0       15    1     0     0   12090
438    107    75     53   9.0 11.5       10    1     1     0    8346
439    165   100     54  12.0  6.5        3    1     0     1   12870
441    150    68     46   9.0 12.0        5    1     1     1   11700
442    165    87     51  12.0 12.7        6    1     0     0   12870
443    180    83     53   8.0 10.5        5    1     0     1   14040
445    129    79     47   8.0 10.5       15    1     0     1   10062
446    145    80     53   9.0  6.0        2    1     1     1   11310
448    131    84     60  10.0  9.0       10    1     0     1   10218
449    168   104     60  16.0 12.0       10    1     0     1   13104
456    140    82     61   6.0  3.5        7    1     1     1   10920
463    147    65     46   8.0  3.0       10    1     0     1   11466
471    115    68     46   7.0 14.5       15    1     0     1    8970
473    372   158     80  20.0 10.5       10    1     0     1   29016
479    133    65     47   8.0 12.5        2    1     0     1   10374
480    212   112     60  17.0  7.0       10    1     0     1   16536
484    205    93     66   9.0  9.0       10    1     1     1   15990
488    145    96     56   9.0 11.0       15    1     1     0   11310
490    130    78     53   9.0  3.5       10    1     1     1   10140
491    112    74     52   7.0 11.0        5    1     1     0    8736
492    130    74     53   7.0  4.5        7    1     1     1   10140
493    222   134     75  16.0 12.0        5    1     0     1   17316
494    153    87     66   9.0  7.5       10    1     1     1   11934
495    108    78     47  10.0 12.0        3    1     0     0    8424
498    155    85     47  11.0 12.7        5    1     0     1   12090
499    155    85     47  11.0 12.7        5    1     0     1   12090
504    135    77     46  10.0 12.7        2    1     0     1   10530
506    180    78     52   8.0  9.0        1    1     1     1   14040
507    139    74     52   9.0 10.5        7    1     0     1   10842
508    145    84     53  10.0 15.5       15    1     0     1   11310
509    219   113     60  20.0  9.0       10    1     0     1   17082
510    185    75     48  10.0  7.0        3    1     1     1   14430
512    150    75     46  11.0  9.0       15    1     0     1   11700
513    145    82     47  10.0 14.5       15    1     0     1   11310
519    210    81     48  10.0  3.0        5    1     1     1   16380
520    113    70     50   9.0  6.0       10    1     0     0    8814
523    156    83     55   9.0 10.5       10    1     1     1   12168
524    160    87     56   9.0  3.0       10    1     0     1   12480
532    145    88     52  12.0  6.5        7    1     1     1   11310
538    270   105     74  10.0  5.0        1    1     1     1   21060
540    110    74     53   8.0 11.0       15    1     1     0    8580
546    140    82     49   8.0 13.0        5    1     0     1   10920
547    115    78     54   8.0 11.5       10    1     1     1    8970
548    195    83     55   9.0  9.0        3    1     1     1   15210
549    150    66     47   9.0  7.0        3    1     0     1   11700
551    145    76     51   8.0  3.0        5    1     1     0   11310
552    162    71     49   9.0  9.0       10    1     1     1   12636
554    130    87     57   7.0 13.5        7    1     1     0   10140
557    110    75     52   9.0 11.5       10    1     1     0    8580
567    132    74     53   7.0  4.5        7    1     1     1   10296
582    155    85     49   9.0 12.0        5    1     1     1   12090
583    145    90     55  10.0  9.0        7    1     1     0   11310
584    170    77     52   7.0  3.0       15    1     1     1   13260
585    140    68     46   7.0  9.0       10    1     0     1   10920
586    156    70     48   7.0  9.0        2    1     1     1   12168
592    165    79     53   9.0  8.0       15    1     1     1   12870
593    105    68     46   8.0 12.0       15    1     0     1    8190
595    227   104     54  10.0 10.5        8    1     0     1   17706
598    280   145     66  16.0 12.7        3    1     0     0   21840
599    165    74     46  10.0  5.0       10    1     0     1   12870
604    170    78     51   9.0 10.5       10    1     1     1   13260
608    170    75     55   8.0  9.0        7    1     1     1   13260
610    180    90     56  11.0  9.0       15    1     0     0   14040
616    133    65     47   8.0 12.5        5    1     0     1   10374
619    415   152     80  17.0  3.0        5    1     0     1   32370
620    140    70     51   8.0 12.5       10    1     1     1   10920
623     97    77     47   9.0 14.5       10    1     0     0    7566
625    157    75     53  10.0 12.5        5    1     0     1   12246
627    185    80     53   9.0  7.5       10    1     1     1   14430
630    110    77     46  11.0 13.0        2    1     0     1    8580
632    120    80     50  10.0  7.0        7    1     0     1    9360
642     93    70     50   9.0 12.5       10    1     0     0    7254
643    105    83     48   9.0 13.0       15    1     0     1    8190
645    142    84     53  10.0 15.5       15    1     0     1   11076
647    132    88     55  14.0 17.0        5    1     0     1   10296
650    142    78     46   9.0 10.5       10    1     1     1   11076
657    164    90     52  13.0 10.0        3    1     1     1   12792
658    164    90     52  13.0 10.0        3    1     1     1   12792
663    135    75     46  10.0 11.0       10    1     0     1   10530
664    145    75     46  10.0  9.0       15    1     0     1   11310
666    160    77     48   8.0 12.0        7    1     1     0   12480
667    140    78     48  11.0 12.7        8    1     0     1   10920
670    105    73     49   8.0 11.5        5    1     0     0    8190
676    135    80     48   8.0 13.0        7    1     0     0   10530
677    160    86     56   9.0  6.0        2    1     0     1   12480
681    170    75     48   7.0  7.5        3    1     1     1   13260
683    110    78     48  14.0 12.0       10    1     0     1    8580
685    205    87     58   9.0  7.5        5    1     1     1   15990
687    160    79     51  12.0  3.0        8    1     1     1   12480
690    137    76     50  15.0 11.0        7    1     1     1   10686
693    130    80     46  10.0 10.5       15    1     0     1   10140
700    140    79     53   8.0  7.0        2    1     0     0   10920
702    125    77     46  10.0 10.5       15    1     0     1    9750
705    130    77     53   9.0  7.0        8    1     1     1   10140
710    190   112     55  16.0  7.0       10    1     0     1   14820
713    108    75     50  10.0 12.0        3    1     0     1    8424

##Задача 8

Выберите из датафрейма flats строки, соответствующие квартирам, которые стоят либо менее 5 млн рублей, либо более 35 млн рублей. Сохраните их в датафрейм flats2.

In [ ]:
flats2 <- flats[flats$priceru * 1000 < 5000000 | flats$priceru * 1000 > 35000000, ]
print(flats2)

     price totsp livesp kitsp dist metrdist walk brick floor priceru
1      730   134    102    10  9.0       10    1     1     1   56940
2      477   119     93    15  9.0        1    1     0     1   37206
5       50    63     47     7 12.0       20    0     1     0    3900
8      470   146     86    16 14.5        5    1     1     1   36660
10     470   120     75    18  9.0       10    1     1     1   36660
11     450   125     80    20  9.0        3    1     0     1   35100
19      52    86     46     9 12.0       10    0     0     1    4056
20     530   150     80    15  7.5        7    1     1     1   41340
31      56    68     43     7 13.5       10    0     1     1    4368
75     460   153     84    18  9.0        5    1     1     1   35880
100    450   145     82    14  4.5        3    1     1     1   35100
108    451   156     80    20 10.5        5    0     1     1   35178
1526   455   192     92    18  7.5        5    1     0     1   35490

##Задача 9

Добавьте в датафрейм flats столбец ratio, который содержит отношение жилой площади квартиры к её общей площади.

In [ ]:
flats$ratio <- flats$livesp / flats$totsp
print(flats)

     price totsp livesp kitsp dist metrdist walk brick floor priceru     ratio
1      730   134    102  10.0  9.0       10    1     1     1   56940 0.7611940
2      477   119     93  15.0  9.0        1    1     0     1   37206 0.7815126
3      350    80     44  14.0 10.5       10    1     1     0   27300 0.5500000
4      410   102     75  10.0  6.5        5    1     1     1   31980 0.7352941
5       50    63     47   7.0 12.0       20    0     1     0    3900 0.7460317
6      340    83     49  19.0  9.0        5    1     1     1   26520 0.5903614
7      285    90     61   6.0 14.5       10    1     0     1   22230 0.6777778
8      470   146     86  16.0 14.5        5    1     1     1   36660 0.5890411
9      135   105     58  21.0 13.5       15    1     1     1   10530 0.5523810
10     470   120     75  18.0  9.0       10    1     1     1   36660 0.6250000
11     450   125     80  20.0  9.0        3    1     0     1   35100 0.6400000
12      87    90     57  13.0 14.5       15    1     1     1    6786 0.6333333
13     142   125     66  19.0 10.5       10    1     0     1   11076 0.5280000
14      73    77     45  10.0  5.0        7    1     0     1    5694 0.5844156
15     126   119     67  17.0 15.5       10    1     0     0    9828 0.5630252
16     350    90     62  12.0 10.5        5    0     0     1   27300 0.6888889
17     270    82     49  13.0  8.0       15    1     0     1   21060 0.5975610
18     420   102     70  20.0  3.0        2    1     1     1   32760 0.6862745
19      52    86     46   9.0 12.0       10    0     0     1    4056 0.5348837
20     530   150     80  15.0  7.5        7    1     1     1   41340 0.5333333
21     127   119     68  15.0 15.5       10    1     0     1    9906 0.5714286
22     170    53     33   9.0  3.0       10    1     1     1   13260 0.6226415
23     116    77     45  18.0  6.0        7    0     0     1    9048 0.5844156
24      84    74     41  12.0  7.0        3    1     0     1    6552 0.5540541
25     350   113     85  20.0  9.0       10    1     0     1   27300 0.7522124
26     130   109     51  16.0 13.5       10    0     1     1   10140 0.4678899
27     223    63     38   7.0  7.5        3    1     1     1   17394 0.6031746
28     285    90     57   7.0  3.0        3    1     0     1   22230 0.6333333
29     175   112     78  16.0  7.0       10    1     1     1   13650 0.6964286
30     190   106     58  24.0  9.0        5    0     0     1   14820 0.5471698
31      56    68     43   7.0 13.5       10    0     1     1    4368 0.6323529
32     310   100     62  17.0  4.5       15    1     0     1   24180 0.6200000
33     100    77     50   6.0  3.5        3    1     1     1    7800 0.6493506
34     135    65     39   7.0 12.0       15    0     0     0   10530 0.6000000
35     260   107     58  14.0 13.0        1    1     0     1   20280 0.5420561
36     125    93     66   9.0  6.0        5    1     1     0    9750 0.7096774
37     220   148     85  14.0 14.5        7    0     1     1   17160 0.5743243
38     280   108     65  14.0 14.5       15    1     1     1   21840 0.6018519
39     299   100     65  11.0  9.0       10    1     0     1   23322 0.6500000
40     147   111     65  16.0 14.5        6    0     1     1   11466 0.5855856
41     174   130     71  16.0 14.5        4    0     0     1   13572 0.5461538
42      92    85     53  10.0 12.0       15    1     1     0    7176 0.6235294
43     207   134     77  21.0 15.5        5    1     0     1   16146 0.5746269
44     360   103     80  14.0  3.0        3    1     1     1   28080 0.7766990
45     260    80     46  12.0  9.0        2    1     1     1   20280 0.5750000
46     160    57     42   8.0  3.5        5    1     1     1   12480 0.7368421
47     250   100     50  15.0 12.7        5    1     0     1   19500 0.5000000
48     352   108     81  16.0  4.5       10    1     1     1   27456 0.7500000
49     210    71     45  15.0  9.0        1    1     1     1   16380 0.6338028
50     170    98     73  12.0  6.0        1    1     1     0   13260 0.7448980
51     210    71     45   6.0  9.0        1    1     1     1   16380 0.6338028
52      99    79     62   6.0 17.0        2    1     1     0    7722 0.7848101
53     260    70     45   8.0  8.0        7    1     1     0   20280 0.6428571
54     340   121     72  13.0 12.5        3    1     1     1   26520 0.5950413
55      82    62     32   7.0  6.0        5    1     1     0    6396 0.5161290
56     215    67     42   9.0  7.5        3    1     1     1   16770 0.6268657
57      72    64     43   7.0  6.0        7    1     0     1    5616 0.6718750
58     252   132     74  23.0 12.5        3    1     1     0   19656 0.5606061
59     199   127     62  20.0 13.5       10    0     1     1   15522 0.4881890
60     371   120     59  15.0  7.0       10    0     0     1   28938 0.4916667
61     371   120     59  15.0  7.0       10    0     0     1   28938 0.4916667
62     250    74     56   8.0  4.5        7    1     1     1   19500 0.7567568
63     151   111     64  16.0 14.5       10    0     1     1   11778 0.5765766
64     160   119     68  10.0 11.0        7    1     1     0   12480 0.5714286
65     190    73     41  11.0  3.5        1    1     1     1   14820 0.5616438
66     180    71     42   8.0  7.0       15    0     0     1   14040 0.5915493
67     299    99     65  11.0  9.0       10    1     1     1   23322 0.6565657
68     250    74     47  10.0  3.0        5    1     1     0   19500 0.6351351
69     200    85     54  14.0 14.5       15    1     0     1   15600 0.6352941
70     210    94     59  11.0 12.7        2    1     1     1   16380 0.6276596
71     132    94     60  11.0  6.5        3    1     0     0   10296 0.6382979
72     150   112     64  16.0 14.5        5    0     0     1   11700 0.5714286
73     120    56     42   6.0 12.0        5    1     1     1    9360 0.7500000
74     330   104     60  11.0 10.5        7    0     1     1   25740 0.5769231
75     460   153     84  18.0  9.0        5    1     1     1   35880 0.5490196
76     370   111     60  13.0  8.0        5    1     1     1   28860 0.5405405
77     380   130     72  15.0  7.0        5    0     0     1   29640 0.5538462
78     126    84     56   9.0  3.5        4    1     1     1    9828 0.6666667
79     299   100     75  12.0  6.5        5    1     1     1   23322 0.7500000
80     150    92     69   8.0  4.5       10    1     1     1   11700 0.7500000
81      79    65     45   7.0  6.0        7    1     0     1    6162 0.6923077
82     120    66     40  19.0  7.5       10    1     1     1    9360 0.6060606
83     230   103     51  14.0 14.5       15    1     1     1   17940 0.4951456
84     210    80     42  20.0  8.0        5    1     0     1   16380 0.5250000
85     160    68     44   8.0 17.0        5    1     0     1   12480 0.6470588
86     230    95     64  10.0 10.5       15    1     1     1   17940 0.6736842
87      90    64     39   9.0  6.0        5    0     1     1    7020 0.6093750
88     150   108     56  15.0 11.0        5    1     1     1   11700 0.5185185
89     200    90     60  10.0 12.0       10    1     1     1   15600 0.6666667
90     190    85     53  12.0 12.0        3    1     0     0   14820 0.6235294
91      96    76     53   8.0  6.0       10    0     1     1    7488 0.6973684
92     130    56     40   5.0  3.5       10    1     1     0   10140 0.7142857
93     185    66     44   6.0  9.0        3    1     1     0   14430 0.6666667
94     240    81     54   8.0  9.0        3    1     1     0   18720 0.6666667
95     150    54     39   6.0  7.0        3    1     1     1   11700 0.7222222
96     135    84     55  11.0  3.0       15    1     1     1   10530 0.6547619
97     110    85     54  10.0  6.0       10    0     1     1    8580 0.6352941
98     130    56     42   7.0 14.5        3    1     1     1   10140 0.7500000
99     120    75     48  11.0  3.0       15    1     1     1    9360 0.6400000
100    450   145     82  14.0  4.5        3    1     1     1   35100 0.5655172
101    180    83     53   8.0 12.0        5    1     1     1   14040 0.6385542
102    170    92     62  18.0  6.0        7    1     1     1   13260 0.6739130
103    315   118     54  12.0  3.5        2    1     1     1   24570 0.4576271
104    160    92     69  14.0  4.5       10    1     1     1   12480 0.7500000
105    245    80     49  10.0  3.0       10    1     1     0   19110 0.6125000
106    152   108     56  15.0 11.0        5    1     1     1   11856 0.5185185
107    113    91     52   9.0  6.5       10    1     1     1    8814 0.5714286
108    451   156     80  20.0 10.5        5    0     1     1   35178 0.5128205
109     73    53     34   6.0  7.5        3    1     1     0    5694 0.6415094
110    309   107     72  17.0 10.5        1    1     1     1   24102 0.6728972
111    245    83     48  12.0  7.5       10    1     1     1   19110 0.5783133
112    170    82     52  20.0  5.0        1    1     0     1   13260 0.6341463
113     75    79     47   8.0 17.0       10    0     0     1    5850 0.5949367
114    145    63     41   8.0  3.5        3    1     0     1   11310 0.6507937
115    130    96     57   9.0  7.5        5    0     1     1   10140 0.5937500
116    270    97     56  18.0  8.0       10    1     1     1   21060 0.5773196
117    109    79     45  13.0 14.5        5    0     1     1    8502 0.5696203
118    371   128     70  18.0  7.0        5    0     0     1   28938 0.5468750
119    125    66     40  10.0 12.0       20    1     0     1    9750 0.6060606
120    212   119     70  17.0  9.0        5    0     1     1   16536 0.5882353
121    115    86     67  13.0 13.5       15    0     0     1    8970 0.7790698
122    120    77     51  12.0  4.5        7    0     1     1    9360 0.6623377
123    132    88     63   8.0  8.0        5    1     1     1   10296 0.7159091
124    235    92     52  15.0  3.5        3    1     0     1   18330 0.5652174
125    250    78     47  10.0 10.5        7    1     0     1   19500 0.6025641
126    171    96     50  18.0  7.0        5    1     0     1   13338 0.5208333
127    120   100     63   9.0 13.0        7    0     0     1    9360 0.6300000
128    110    51     34   6.0  3.5        7    1     0     1    8580 0.6666667
129     90    72     53  10.0 11.5        5    0     1     1    7020 0.7361111
130    135    75     43  11.0 12.7       15    1     0     1   10530 0.5733333
131    227   134     70  16.0  9.0        5    1     0     1   17706 0.5223881
132    215    76     55   8.0  7.5        2    1     1     1   16770 0.7236842
133    210    72     49   7.0  7.5        5    1     1     1   16380 0.6805556
134    200    77     46  10.0  3.0       15    1     1     1   15600 0.5974026
135     85    65     43   5.0  7.5        5    1     1     1    6630 0.6615385
136    125    63     43   6.0 17.0        5    1     1     1    9750 0.6825397
137    220    81     46  13.0  9.0        7    1     0     1   17160 0.5679012
138    114    83     46  12.0  7.0       10    1     0     1    8892 0.5542169
139    210    80     49  10.0 12.5        5    1     1     1   16380 0.6125000
140    225   101     65  15.0 10.5       20    1     1     1   17550 0.6435644
141    109    79     45  13.0 14.5        7    0     1     1    8502 0.5696203
142    201    82     55   9.0 13.5        7    1     0     1   15678 0.6707317
143    100    77     52   9.0 10.5       15    0     1     1    7800 0.6753247
144    260   135     75  20.0 12.5        3    1     1     0   20280 0.5555556
145    130    86     54  13.0  6.0       10    1     0     1   10140 0.6279070
146    193    78     55   8.0  7.5       10    1     0     1   15054 0.7051282
147    196    78     46  10.0 14.5        5    1     0     1   15288 0.5897436
148    115    57     38   8.0 12.0        5    1     0     1    8970 0.6666667
149    120    76     49   9.0  3.0       10    1     1     0    9360 0.6447368
150    115    77     51   7.0  5.0        5    1     1     0    8970 0.6623377
151     97    80     48   8.0 13.0        5    0     1     1    7566 0.6000000
152    230    80     46  13.0  5.0        4    1     1     1   17940 0.5750000
153    167   113     64  13.0 14.5        5    0     1     1   13026 0.5663717
154    160   114     67  15.0 14.5       10    0     0     1   12480 0.5877193
155    105    72     52   8.0  6.0       15    0     1     1    8190 0.7222222
156    200   121     71  12.0 10.0        3    1     0     1   15600 0.5867769
157    200    72     46   9.0  9.0       10    1     1     1   15600 0.6388889
158    197    70     46   7.0  4.5        3    1     1     1   15366 0.6571429
159    140    56     40   5.0  9.0        5    1     1     0   10920 0.7142857
160    149    77     45  10.0 13.0        2    1     0     1   11622 0.5844156
161    160    84     50   9.0 12.7        1    1     0     1   12480 0.5952381
162    165    99     70   9.0  7.5        7    0     1     1   12870 0.7070707
163     95    63     42   8.0  3.5        5    1     1     1    7410 0.6666667
164    170    81     60  13.0 13.0        5    1     0     1   13260 0.7407407
165    116    75     51   9.0  3.5        5    0     1     0    9048 0.6800000
166    140    99     51  12.0 10.5        1    1     0     0   10920 0.5151515
167    153    80     40  25.0 10.5       10    0     0     1   11934 0.5000000
168    163   115     66  15.0 13.5       10    0     0     1   12714 0.5739130
169    226    82     52  10.0  3.0        3    1     0     1   17628 0.6341463
170    114    93     51  12.0 10.0        7    1     0     0    8892 0.5483871
171    129    99     55  11.0 10.5       15    1     0     0   10062 0.5555556
172    125    83     53  10.0  5.0       12    1     0     0    9750 0.6385542
173    180    79     45  10.0  8.0       15    1     0     1   14040 0.5696203
174    145    74     45  10.0 15.5       15    1     0     1   11310 0.6081081
175    141   113     58  13.0 13.5       10    0     0     1   10998 0.5132743
176     78    63     47   6.0 13.5        5    0     1     1    6084 0.7460317
177    185    78     53   8.0  7.5       15    1     1     1   14430 0.6794872
178    225    80     56   9.0  9.0        5    1     1     1   17550 0.7000000
179    170    86     56  10.0 12.0        2    1     0     1   13260 0.6511628
180    147    77     44  10.0 13.0        2    1     0     1   11466 0.5714286
181    220    83     53   9.0  4.5        5    1     0     0   17160 0.6385542
182    179    65     45   8.0  9.0        5    1     1     1   13962 0.6923077
183    265   100     56  14.0  7.0       10    0     0     1   20670 0.5600000
184    245    85     54  12.0  9.0        7    1     1     1   19110 0.6352941
185     88    72     51   9.0 11.5       10    0     1     1    6864 0.7083333
186    177    74     45   8.0  5.0       15    1     1     1   13806 0.6081081
187    155    60     40  11.0  7.5        5    1     1     1   12090 0.6666667
188    105    75     50   8.0  6.5       15    1     1     0    8190 0.6666667
189    199    70     46   8.0  7.5        7    1     1     1   15522 0.6571429
190    230   109     58  18.0 12.7        2    1     0     1   17940 0.5321101
191    220   100     49  13.0 14.5       10    1     1     1   17160 0.4900000
192    100    83     53  10.0 12.0       15    0     0     0    7800 0.6385542
193    170    65     45   7.0  7.5        2    1     1     1   13260 0.6923077
194    125    81     56   9.0  6.0        5    1     1     0    9750 0.6913580
195    200    71     46   8.0  4.5        5    1     1     0   15600 0.6478873
196    101    62     43   6.0 12.0       15    1     0     1    7878 0.6935484
197     78    64     39   8.0  7.0       10    0     0     1    6084 0.6093750
198     72    60     42   6.0 11.5       10    0     1     0    5616 0.7000000
199    110    77     46  10.0  6.0       10    0     0     1    8580 0.5974026
200     98    74     46  11.0 12.5       10    0     1     0    7644 0.6216216
201    110    86     53   9.0 10.5        5    0     0     0    8580 0.6162791
202    220    77     49  10.0  7.5        5    1     1     1   17160 0.6363636
203    155    64     36   8.0  8.0        7    1     1     0   12090 0.5625000
204    155    60     40   8.0  7.5        5    1     1     1   12090 0.6666667
205    194   106     60  17.0  9.0        5    0     1     1   15132 0.5660377
206    142    83     45  10.0 12.7       15    1     0     1   11076 0.5421687
207    170    86     59  10.0 17.0       10    0     1     1   13260 0.6860465
208    103    78     54  11.0 12.0       15    1     1     0    8034 0.6923077
209    159   109     64  13.0 14.5       10    0     1     1   12402 0.5871560
210     95    74     45   8.0 14.5        5    0     1     0    7410 0.6081081
211    115    77     50   9.0  3.5        7    1     0     0    8970 0.6493506
212    175    81     47  10.0 14.5       10    0     1     1   13650 0.5802469
213    112    79     45   8.0 11.5        2    1     1     1    8736 0.5696203
214    175    79     47   9.0 14.5        7    1     1     1   13650 0.5949367
215    200    78     50   7.0  8.0       10    1     1     1   15600 0.6410256
216     89    79     52  10.0 15.5       10    1     0     1    6942 0.6582278
217    118    71     41   8.0 12.0       15    0     0     1    9204 0.5774648
218     93    78     46  10.0 12.0       15    0     0     1    7254 0.5897436
219    160    77     45  10.0 12.0       15    1     0     1   12480 0.5844156
220    132    84     52  11.0 12.7       20    1     0     1   10296 0.6190476
221     85    59     44   6.0  7.0        1    1     0     1    6630 0.7457627
222    150    75     51   8.0 12.0       15    1     0     0   11700 0.6800000
223    250    92     57  11.0  9.0        3    1     1     1   19500 0.6195652
224     98    79     48  10.0 12.0       10    1     1     1    7644 0.6075949
225    122    93     52  14.0 13.5       10    1     0     1    9516 0.5591398
226    130    82     37  12.0  6.0       10    1     0     1   10140 0.4512195
227    138    95     63   9.0 10.0       10    1     0     1   10764 0.6631579
228    225    80     53   9.0  7.0        5    1     1     1   17550 0.6625000
229     99    72     50   9.0  7.5       10    0     1     1    7722 0.6944444
230    230    92     60  14.0  9.0       10    1     0     0   17940 0.6521739
231    100    83     48  10.0 12.0       15    0     0     0    7800 0.5783133
232     81    53     34   6.0 13.0       15    1     0     0    6318 0.6415094
233     96    60     43   6.0 12.0       15    1     0     1    7488 0.7166667
234    208   115     70  14.0 10.0        3    1     1     1   16224 0.6086957
235    170    68     39  10.0  4.5       10    1     1     0   13260 0.5735294
236     70    58     41   6.0 14.5       10    0     1     1    5460 0.7068966
237    166    77     45  11.0 10.5       15    1     1     1   12948 0.5844156
238    150    78     44  10.0 14.5       15    1     0     1   11700 0.5641026
239    190    72     46  10.0  9.0        5    1     1     1   14820 0.6388889
240    167    74     43  10.0 14.5        5    1     0     1   13026 0.5810811
241    165    65     45   9.0  9.0       10    1     1     1   12870 0.6923077
242    165    65     45   9.0  9.0       10    1     1     1   12870 0.6923077
243     84    76     45  10.0 17.0       10    1     0     1    6552 0.5921053
244    130    78     53  13.0  3.5       10    1     1     1   10140 0.6794872
245    185    80     53   9.0  7.5       15    1     1     1   14430 0.6625000
246    180    71     47   7.0  7.5       10    1     1     1   14040 0.6619718
247    220   103     49  13.0 14.5       10    1     1     1   17160 0.4757282
248     78    55     37   6.0 11.5        2    1     1     1    6084 0.6727273
249     78    55     37   6.0 11.5        2    1     1     1    6084 0.6727273
250    165    90     65   8.0  6.0        2    1     1     1   12870 0.7222222
251    159   107     64  13.0 14.5       10    0     1     1   12402 0.5981308
252    200   122     68  12.0 10.0        5    1     0     1   15600 0.5573770

##Задача 10

Выберите из датафрейма flats строки, соответствующие квартирам со значением ratio более 0,8. Обязательно ли квартиры с большой долей жилой площади самые дорогие? Приведите код и ответ на вопрос.

In [ ]:
flats10 <- flats[flats$ratio > 0.8, ]
print(flats10)

#Обязательно ли квартиры с большой долей жилой площади самые дорогие? Нет, не обязательно.

     price totsp livesp kitsp dist metrdist walk brick floor priceru     ratio
1264    90    61     49     6   12       10    1     0     1    7020 0.8032787
1616    82    57     46     6   12       10    1     1     1    6396 0.8070175

Задача 11

Выберите из датафрейма столбцы totsp, livesp, kitsp и сохраните их в датафрейм space. Переименуйте столбцы, присвоив им названия total, live и kitchen.

In [ ]:
space <- flats[, c('totsp', 'livesp', 'kitsp')]
colnames(space) <- c('total', 'live', 'kitchen')
print(space)

     total live kitchen
1      134  102    10.0
2      119   93    15.0
3       80   44    14.0
4      102   75    10.0
5       63   47     7.0
6       83   49    19.0
7       90   61     6.0
8      146   86    16.0
9      105   58    21.0
10     120   75    18.0
11     125   80    20.0
12      90   57    13.0
13     125   66    19.0
14      77   45    10.0
15     119   67    17.0
16      90   62    12.0
17      82   49    13.0
18     102   70    20.0
19      86   46     9.0
20     150   80    15.0
21     119   68    15.0
22      53   33     9.0
23      77   45    18.0
24      74   41    12.0
25     113   85    20.0
26     109   51    16.0
27      63   38     7.0
28      90   57     7.0
29     112   78    16.0
30     106   58    24.0
31      68   43     7.0
32     100   62    17.0
33      77   50     6.0
34      65   39     7.0
35     107   58    14.0
36      93   66     9.0
37     148   85    14.0
38     108   65    14.0
39     100   65    11.0
40     111   65    16.0
41     130   71    16.0
42      85   53    10.0
43     134   77    21.0
44     103   80    14.0
45      80   46    12.0
46      57   42     8.0
47     100   50    15.0
48     108   81    16.0
49      71   45    15.0
50      98   73    12.0
51      71   45     6.0
52      79   62     6.0
53      70   45     8.0
54     121   72    13.0
55      62   32     7.0
56      67   42     9.0
57      64   43     7.0
58     132   74    23.0
59     127   62    20.0
60     120   59    15.0
61     120   59    15.0
62      74   56     8.0
63     111   64    16.0
64     119   68    10.0
65      73   41    11.0
66      71   42     8.0
67      99   65    11.0
68      74   47    10.0
69      85   54    14.0
70      94   59    11.0
71      94   60    11.0
72     112   64    16.0
73      56   42     6.0
74     104   60    11.0
75     153   84    18.0
76     111   60    13.0
77     130   72    15.0
78      84   56     9.0
79     100   75    12.0
80      92   69     8.0
81      65   45     7.0
82      66   40    19.0
83     103   51    14.0
84      80   42    20.0
85      68   44     8.0
86      95   64    10.0
87      64   39     9.0
88     108   56    15.0
89      90   60    10.0
90      85   53    12.0
91      76   53     8.0
92      56   40     5.0
93      66   44     6.0
94      81   54     8.0
95      54   39     6.0
96      84   55    11.0
97      85   54    10.0
98      56   42     7.0
99      75   48    11.0
100    145   82    14.0
101     83   53     8.0
102     92   62    18.0
103    118   54    12.0
104     92   69    14.0
105     80   49    10.0
106    108   56    15.0
107     91   52     9.0
108    156   80    20.0
109     53   34     6.0
110    107   72    17.0
111     83   48    12.0
112     82   52    20.0
113     79   47     8.0
114     63   41     8.0
115     96   57     9.0
116     97   56    18.0
117     79   45    13.0
118    128   70    18.0
119     66   40    10.0
120    119   70    17.0
121     86   67    13.0
122     77   51    12.0
123     88   63     8.0
124     92   52    15.0
125     78   47    10.0
126     96   50    18.0
127    100   63     9.0
128     51   34     6.0
129     72   53    10.0
130     75   43    11.0
131    134   70    16.0
132     76   55     8.0
133     72   49     7.0
134     77   46    10.0
135     65   43     5.0
136     63   43     6.0
137     81   46    13.0
138     83   46    12.0
139     80   49    10.0
140    101   65    15.0
141     79   45    13.0
142     82   55     9.0
143     77   52     9.0
144    135   75    20.0
145     86   54    13.0
146     78   55     8.0
147     78   46    10.0
148     57   38     8.0
149     76   49     9.0
150     77   51     7.0
151     80   48     8.0
152     80   46    13.0
153    113   64    13.0
154    114   67    15.0
155     72   52     8.0
156    121   71    12.0
157     72   46     9.0
158     70   46     7.0
159     56   40     5.0
160     77   45    10.0
161     84   50     9.0
162     99   70     9.0
163     63   42     8.0
164     81   60    13.0
165     75   51     9.0
166     99   51    12.0
167     80   40    25.0
168    115   66    15.0
169     82   52    10.0
170     93   51    12.0
171     99   55    11.0
172     83   53    10.0
173     79   45    10.0
174     74   45    10.0
175    113   58    13.0
176     63   47     6.0
177     78   53     8.0
178     80   56     9.0
179     86   56    10.0
180     77   44    10.0
181     83   53     9.0
182     65   45     8.0
183    100   56    14.0
184     85   54    12.0
185     72   51     9.0
186     74   45     8.0
187     60   40    11.0
188     75   50     8.0
189     70   46     8.0
190    109   58    18.0
191    100   49    13.0
192     83   53    10.0
193     65   45     7.0
194     81   56     9.0
195     71   46     8.0
196     62   43     6.0
197     64   39     8.0
198     60   42     6.0
199     77   46    10.0
200     74   46    11.0
201     86   53     9.0
202     77   49    10.0
203     64   36     8.0
204     60   40     8.0
205    106   60    17.0
206     83   45    10.0
207     86   59    10.0
208     78   54    11.0
209    109   64    13.0
210     74   45     8.0
211     77   50     9.0
212     81   47    10.0
213     79   45     8.0
214     79   47     9.0
215     78   50     7.0
216     79   52    10.0
217     71   41     8.0
218     78   46    10.0
219     77   45    10.0
220     84   52    11.0
221     59   44     6.0
222     75   51     8.0
223     92   57    11.0
224     79   48    10.0
225     93   52    14.0
226     82   37    12.0
227     95   63     9.0
228     80   53     9.0
229     72   50     9.0
230     92   60    14.0
231     83   48    10.0
232     53   34     6.0
233     60   43     6.0
234    115   70    14.0
235     68   39    10.0
236     58   41     6.0
237     77   45    11.0
238     78   44    10.0
239     72   46    10.0
240     74   43    10.0
241     65   45     9.0
242     65   45     9.0
243     76   45    10.0
244     78   53    13.0
245     80   53     9.0
246     71   47     7.0
247    103   49    13.0
248     55   37     6.0
249     55   37     6.0
250     90   65     8.0
251    107   64    13.0
252    122   68    12.0
253     58   40     7.0
254     72   48     7.0
255     77   43    11.0
256     76   43    10.0
257     68   47     8.0
258     77   51     8.0
259     68   40     9.0
260     84   52    11.0
261     64   44     9.0
262     86   54    10.0
263     77   45    10.0
264     92   57    12.0
265     69   42     9.0
266     56   41     5.0
267     77   50     9.0
268     92   50    14.0
269     96   56    12.0
270     95   51    11.0
271     74   45    11.0
272     92   50    11.0
273     74   43    10.0
274     84   54     8.0
275     82   48     8.0
276     75   42    11.0
277     80   45    13.0
278     96   58    14.0
279    125   70    18.0
280     79   53     8.0
281     81   48     9.0
282     85   58    13.0
283     58   30     6.0
284     78   50     8.0
285     73   49     9.0
286     73   49     9.0
287     75   40    11.0
288     76   45    10.0
289     58   44     5.0
290     52   34     6.0
291     80   45    13.0
292     80   45    13.0
293     82   52    15.0
294     80   45    12.0
295     96   54    12.0
296     80   48     9.0
297     81   46    12.0
298    106   71     9.0
299     56   37     6.0
300     82   50    10.0
301     57   42     6.0
302     70   39     9.0
303     79   45    13.0
304     80   45    10.0
305     81   56     9.0
306     81   56     9.0
307     73   47     6.0
308    106   63    12.0
309     75   47     8.0
310     82   54     8.0
311     67   39     8.0
312     97   63    11.0
313     80   48    10.0
314     58   43     5.0
315    108   60    13.0
316     61   43     6.0
317     67   46     9.0
318     53   35     7.0
319     53   35     7.0
320     75   52     9.0
321     76   44    10.0
322     56   41     6.0
323     96   52    10.0
324     54   35     5.0
325    102   70     9.0
326     59   39     6.0
327     60   41     6.0
328     80   51     9.0
329     75   45    10.0
330     66   42     6.0
331     75   50     8.0
332     62   38     9.0
333     80   50     8.0
334     90   57     8.0
335     78   45    10.0
336     78   48    13.0
337     96   51    12.0
338     75   45    10.0
339    110   56    15.0
340     77   43    10.0
341    123   68    16.0
342     74   45    10.0
343     74   45     8.0
344     58   43     6.0
345     78   45    10.0
346     73   54     9.0
347     57   38     6.0
348     58   42     5.0
349     53   34     6.0
350     70   48     7.0
351     62   41     9.0
352     73   52     8.0
353     95   62    11.0
354     58   40     6.0
355     86   51     8.0
356    105   55    14.0
357    100   66    21.0
358     64   44     7.0
359     77   45    10.0
360     78   46    10.0
361     65   39     8.0
362     83   44    10.0
363     54   34     6.0
364     75   52     9.0
365    101   51    15.0
366     65   39     8.0
367     78   54     9.0
368     78   50    10.0
369     80   44    13.0
370     93   57     9.0
371     54   34     6.0
372     66   44     9.0
373     51   35     6.0
374     70   40     9.0
375     60   43     6.0
376    127   66    15.0
377     58   44     6.0
378     67   46     8.0
379     72   46    11.0
380     51   35     6.0
381     72   53     8.0
382     79   45    10.0
383     55   40     5.0
384     75   51     9.0
385     57   37     6.0
386     59   45     6.0
387     72   44     7.0
388     75   48     9.0
389     88   59     9.0
390     59   44     6.0
391     65   45     7.0
392     70   40     8.0
393     56   37     5.0
394     70   40     8.0
395     78   44     9.0
396     61   45     6.0
397     76   44    10.0
398     92   48    13.0
399     74   45    11.0
400     64   38     8.0
401     85   46    14.0
402     71   47     8.0
403     80   45    13.0
404     55   38     6.0
405     59   38     6.0
406     90   61     9.0
407     55   41     5.0
408     82   48     8.0
409     70   44     8.0
410    136   88    14.0
411     89   51    12.0
412     77   54     9.0
413     75   44     8.0
414     63   38     8.0
415     72   51     8.0
416     72   51     8.0
417     85   52     9.0
418     54   38     6.0
419     60   43     6.0
420     87   57     7.0
421    100   56    12.0
422    105   56    12.0
423     57   42     6.0
424     68   40     8.0
425     75   45    10.0
426     69   47     7.0
427     58   43     6.0
428     68   42     8.0
429     80   51    10.0
430     64   40     7.0
431     55   36     6.0
432     73   46    10.0
433     79   56     8.0
434     85   50     8.0
435     75   43    11.0
436     60   40     5.0
437     80   46    13.0
438     75   53     9.0
439    100   54    12.0
440     57   41     6.0
441     68   46     9.0
442     87   51    12.0
443     83   53     8.0
444     57   42     6.0
445     79   47     8.0
446     80   53     9.0
447     60   43     6.0
448     84   60    10.0
449    104   60    16.0
450     74   51     8.0
451     78   45    10.0
452     84   45    11.0
453     56   37     6.0
454     56   39     5.0
455     56   37     6.0
456     82   61     6.0
457     50   32     5.0
458     72   45     9.0
459     68   32    13.0
460     79   51    10.0
461     75   45    10.0
462     83   53    12.0
463     65   46     8.0
464     90   58    11.0
465     77   41    11.0
466     57   43     6.0
467     77   45    10.0
468     58   43     5.0
469     74   43    10.0
470     64   39     9.0
471     68   46     7.0
472     80   50     8.0
473    158   80    20.0
474     59   44     6.0
475     78   44     8.0
476     61   40     8.0
477     58   45     6.0
478     66   43     7.0
479     65   47     8.0
480    112   60    17.0
481     64   43     7.0
482     60   43     6.0
483     66   44     9.0
484     93   66     9.0
485     73   45     8.0
486     54   42     6.0
487     75   45    10.0
488     96   56     9.0
489     60   42     7.0
490     78   53     9.0
491     74   52     7.0
492     74   53     7.0
493    134   75    16.0
494     87   66     9.0
495     78   47    10.0
496     66   47     8.0
497     75   45    10.0
498     85   47    11.0
499     85   47    11.0
500     54   34     6.0
501     95   58    14.0
502     65   43    10.0
503     59   41     6.0
504     77   46    10.0
505     72   52     9.0
506     78   52     8.0
507     74   52     9.0
508     84   53    10.0
509    113   60    20.0
510     75   48    10.0
511     79   45    13.0
512     75   46    11.0
513     82   47    10.0
514     74   52     9.0
515     56   39     5.0
516     79   47     8.0
517     56   38     6.0
518     58   43     5.0
519     81   48    10.0
520     70   50     9.0
521     82   53     9.0
522     58   37     5.0
523     83   55     9.0
524     87   56     9.0
525     59   42     6.0
526     77   45    10.0
527     60   44     6.0
528     75   45    10.0
529     87   55    10.0
530     84   54    10.0
531     76   45    10.0
532     88   52    12.0
533     55   36     6.0
534     69   43     7.0
535     58   40     6.0
536     77   45    13.0
537     59   39     6.0
538    105   74    10.0
539     73   41    10.0
540     74   53     8.0
541     57   38     6.0
542     77   44    10.0
543     80   53     8.0
544     69   40     9.0
545     63   37     8.0
546     82   49     8.0
547     78   54     8.0
548     83   55     9.0
549     66   47     9.0
550     58   35    11.0
551     76   51     8.0
552     71   49     9.0
553     72   43     9.0
554     87   57     7.0
555     65   43     7.0
556    101   60    15.0
557     75   52     9.0
558     58   38     6.0
559     74   45    11.0
560     72   43     9.0
561     60   37     8.0
562     73   41     8.0
563     53   39     5.0
564     67   45     8.0
565     79   45    13.0
566     79   45    13.0
567     74   53     7.0
568     51   34     6.0
569     55   34     5.0
570     66   43     9.0
571     74   43    10.0
572     72   43    12.0
573     72   43    12.0
574     74   45    10.0
575     74   45    10.0
576     75   42     8.0
577     75   42     8.0
578     59   44     6.0
579     70   50     6.0
580     75   44    10.0
581     58   42     6.0
582     85   49     9.0
583     90   55    10.0
584     77   52     7.0
585     68   46     7.0
586     70   48     7.0
587     86   55    10.0
588     69   48     6.0
589     61   38     8.0
590     63   38     8.0
591     58   42     6.0
592     79   53     9.0
593     68   46     8.0
594     80   45    13.0
595    104   54    10.0
596     62   40     8.0
597     85   50     9.0
598    145   66    16.0
599     74   46    10.0
600     77   46    11.0
601     58   45     5.0
602     56   37     5.0
603     79   47     8.0
604     78   51     9.0
605     60   45     6.0
606     51   34     6.0
607     81   43    10.0
608     75   55     8.0
609     59   39     6.0
610     90   56    11.0
611     70   47     8.0
612     59   38     8.0
613     60   39     6.0
614     55   36     6.0
615     76   44     9.0
616     65   47     8.0
617     78   44     8.0
618     69   47     7.0
619    152   80    17.0
620     70   51     8.0
621     57   41     6.0
622     55   40     6.0
623     77   47     9.0
624     77   45     7.0
625     75   53    10.0
626     78   54     7.0
627     80   53     9.0
628     60   43     6.0
629     64   44     9.0
630     77   46    11.0
631     79   52    10.0
632     80   50    10.0
633     60   44     6.0
634     74   45    10.0
635     60   44     6.0
636     55   38     6.0
637     78   45    10.0
638     63   45     6.0
639     65   40     8.0
640     79   45    13.0
641     44   28     6.0
642     70   50     9.0
643     83   48     9.0
644     60   41     8.0
645     84   53    10.0
646     85   53    12.0
647     88   55    14.0
648     75   45    10.0
649     74   45    12.0
650     78   46     9.0
651     77   44    10.0
652     51   34     6.0
653     62   42    10.0
654     85   45    10.0
655     70   45     9.0
656     56   38     6.0
657     90   52    13.0
658     90   52    13.0
659     54   36     6.0
660     78   44    11.0
661     51   34     6.0
662     67   37     7.0
663     75   46    10.0
664     75   46    10.0
665     57   40     6.0
666     77   48     8.0
667     78   48    11.0
668     49   34     6.0
669     55   36     6.0
670     73   49     8.0
671     56   42     5.0
672     56   42     5.0
673     77   42     8.0
674     59   43     5.0
675     76   45    10.0
676     80   48     8.0
677     86   56     9.0
678     77   45    10.0
679     75   45    10.0
680     60   41     6.0
681     75   48     7.0
682     60   45     6.0
683     78   48    14.0
684     55   39     6.0
685     87   58     9.0
686     59   40     6.0
687     79   51    12.0
688     66   43     7.0
689     73   51     8.0
690     76   50    15.0
691     54   35     6.0
692     57   42     6.0
693     80   46    10.0
694     70   42     6.0
695     80   45    13.0
696     82   45    10.0
697     58   39     7.0
698     59   38     6.0
699     86   55    10.0
700     79   53     8.0
701     72   46    10.0
702     77   46    10.0
703     67   42     9.0
704     72   43    12.0
705     77   53     9.0
706     77   44    10.0
707     60   45     6.0
708     58   38     6.0
709     56   36     6.0
710    112   55    16.0
711     75   45    10.0
712     75   45    10.0
713     75   50    10.0
714     70   45     9.0
715     64   47     6.0
716     70   50     8.0
717     79   52     9.0
718     74   44    10.0
719     58   41     6.0
720     56   37     6.0
721     53   36     5.0
722     53   36     5.0
723     76   44    10.0
724     83   44    10.0
725     55   36     6.0
726     87   60    15.0
727     79   45    13.0
728     61   44     7.0
729     68   43     9.0
730     95   57     8.0
731     55   35     6.0
732     73   47     9.0
733     56   37     6.0
734     80   45    13.0
735     78   45    10.0
736     76   45    10.0
737     56   41     5.0
738     65   45    11.0
739     77   54     8.0
740     72   45    10.0
741     78   46     9.0
742     77   50     8.0
743     85   54    11.0
744     78   44    13.0
745     78   54     8.0
746     55   36     6.0
747     86   51    11.0
748     59   43     6.0
749     65   40     7.0
750     66   41     8.0
751     65   38     8.0
752     74   54     9.0
753     77   45    11.0
754     80   54    12.0
755     76   43    12.0
756     55   38     6.0
757     70   40     6.0
758     72   44     9.0
759     77   40    11.0
760     74   48    11.0
761     74   45    10.0
762     85   53     9.0
763     61   41     6.0
764     84   53    12.0
765     74   43    10.0
766     71   43    10.0
767     74   48    10.0
768     57   42     6.0
769     81   51    14.0
770     75   46    10.0
771     54   34     6.0
772     60   43     6.0
773     75   53     8.0
774     95   57    12.0
775     60   38     6.0
776     59   46     6.0
777     80   47    10.0
778     78   52     9.0
779     60   43     6.0
780     64   35     6.0
781     66   45     8.0
782     56   39     6.0
783     60   41     6.0
784     69   47     8.0
785     73   51     8.0
786     73   43    11.0
787     52   34     6.0
788     81   44    10.0
789     75   45    10.0
790     68   46     8.0
791     51   34     6.0
792     62   44     6.0
793     76   45    11.0
794     80   48    13.0
795     79   44    13.0
796     80   55     8.0
797     58   42     5.0
798     84   53    10.0
799     50   34     6.0
800     76   43    10.0
801     56   34     7.0
802     77   46     9.0
803     52   36     6.0
804    106   64    13.0
805     76   48     9.0
806     56   37     6.0
807     64   39     8.0
808     73   43    11.0
809    104   55    11.0
810     80   45    13.0
811     64   38     8.0
812     60   42     7.0
813     82   44    10.0
814     76   40    11.0
815     90   61    10.0
816     68   46     8.0
817     80   46    10.0
818     60   44     6.0
819     60   40     8.0
820     85   46    10.0
821     83   56    10.0
822     66   44     9.0
823     54   36     5.0
824     78   53     8.0
825     75   47     9.0
826     65   39     8.0
827     78   54     8.0
828     94   57     8.0
829     74   44    10.0
830     86   55    10.0
831     68   45    10.0
832     76   45    10.0